import { IconGroup } from "./types";

export const ICON_GROUPS: IconGroup[] = [
  {
    name: "Smileys",
    items: [
      {
        id: "grinning",
        name: "Grinning Face",
        unicode: "😀",
        keywords: ["happy", "smile", "face"],
      },
      {
        id: "smiley",
        name: "Grinning Face with Big Eyes",
        unicode: "😃",
        keywords: ["happy", "smile", "joy"],
      },
      {
        id: "smile",
        name: "Grinning Face with Smiling Eyes",
        unicode: "😄",
        keywords: ["happy", "smile", "joy"],
      },
      {
        id: "grin",
        name: "Beaming Face with Smiling Eyes",
        unicode: "😁",
        keywords: ["happy", "smile"],
      },
      {
        id: "laughing",
        name: "Grinning Squinting Face",
        unicode: "😆",
        keywords: ["happy", "laugh", "joy"],
      },
      {
        id: "sweatsmile",
        name: "Grinning Face with Sweat",
        unicode: "😅",
        keywords: ["happy", "laugh"],
      },
      {
        id: "rofl",
        name: "Rolling on the Floor Laughing",
        unicode: "🤣",
        keywords: ["laugh", "happy"],
      },
      {
        id: "joy",
        name: "Face with Tears of Joy",
        unicode: "😂",
        keywords: ["laugh", "happy", "cry"],
      },
      {
        id: "slightlysmilingface",
        name: "Slightly Smiling Face",
        unicode: "🙂",
        keywords: ["happy", "smile"],
      },
      {
        id: "upsidedownface",
        name: "Upside Down Face",
        unicode: "🙃",
        keywords: ["sarcasm", "funny"],
      },
      {
        id: "wink",
        name: "Winking Face",
        unicode: "😉",
        keywords: ["flirt", "happy"],
      },
      {
        id: "blush",
        name: "Smiling Face with Smiling Eyes",
        unicode: "😊",
        keywords: ["happy", "kind"],
      },
      {
        id: "innocent",
        name: "Smiling Face with Halo",
        unicode: "😇",
        keywords: ["angel", "good"],
      },
      {
        id: "heart-eyes",
        name: "Smiling Face with Heart Eyes",
        unicode: "😍",
        keywords: ["love", "heart"],
      },
      {
        id: "starstruck",
        name: "Smiling Face with Star Eyes",
        unicode: "🤩",
        keywords: ["star", "wow"],
      },
      {
        id: "kissingheart",
        name: "Face Blowing a Kiss",
        unicode: "😘",
        keywords: ["love", "kiss"],
      },
      {
        id: "kissing",
        name: "Kissing Face",
        unicode: "😗",
        keywords: ["kiss", "love"],
      },
      {
        id: "kissingclosedeyes",
        name: "Kissing Face with Closed Eyes",
        unicode: "😚",
        keywords: ["kiss", "love"],
      },
      {
        id: "kissingsmilingeyes",
        name: "Kissing Face with Smiling Eyes",
        unicode: "😙",
        keywords: ["kiss", "love"],
      },
      {
        id: "smilingfacewithtear",
        name: "Smiling Face with Tear",
        unicode: "🥲",
        keywords: ["happy", "tear"],
      },
      {
        id: "yum",
        name: "Face Savoring Food",
        unicode: "😋",
        keywords: ["tasty", "delicious"],
      },
      {
        id: "stuckouttongue",
        name: "Tongue Out",
        unicode: "😛",
        keywords: ["playful", "silly"],
      },
      {
        id: "stuckouttonguewinkingeye",
        name: "Winking with Tongue",
        unicode: "😜",
        keywords: ["playful", "silly"],
      },
      {
        id: "zanyface",
        name: "Zany Face",
        unicode: "🤪",
        keywords: ["crazy", "playful"],
      },
      {
        id: "relieved",
        name: "Relieved Face",
        unicode: "😌",
        keywords: ["calm", "peaceful"],
      },
      {
        id: "pensive",
        name: "Pensive Face",
        unicode: "😔",
        keywords: ["sad", "thinking"],
      },
      {
        id: "expressionless",
        name: "Expressionless Face",
        unicode: "😑",
        keywords: ["flat", "unimpressed"],
      },
      {
        id: "neutralface",
        name: "Neutral Face",
        unicode: "😐",
        keywords: ["meh", "no emotion"],
      },
      {
        id: "nomouth",
        name: "Face Without Mouth",
        unicode: "😶",
        keywords: ["silence", "secret"],
      },
      {
        id: "smirk",
        name: "Smirking Face",
        unicode: "😏",
        keywords: ["cocky", "sly"],
      },
      {
        id: "unamused",
        name: "Unamused Face",
        unicode: "😒",
        keywords: ["unimpressed", "sarcasm"],
      },
      {
        id: "frowning",
        name: "Frowning Face",
        unicode: "☹️",
        keywords: ["sad", "unhappy"],
      },
      {
        id: "grimacing",
        name: "Grimacing Face",
        unicode: "😬",
        keywords: ["awkward", "uncomfortable"],
      },
      {
        id: "lyingface",
        name: "Lying Face",
        unicode: "🤥",
        keywords: ["liar", "dishonest"],
      },
      {
        id: "sleepy",
        name: "Sleepy Face",
        unicode: "😪",
        keywords: ["tired", "sleep"],
      },
      {
        id: "droolingface",
        name: "Drooling Face",
        unicode: "🤤",
        keywords: ["yum", "hungry"],
      },
      {
        id: "sleeping",
        name: "Sleeping Face",
        unicode: "😴",
        keywords: ["sleep", "zzz"],
      },
      {
        id: "mask",
        name: "Face with Medical Mask",
        unicode: "😷",
        keywords: ["sick", "health"],
      },
      {
        id: "facewiththermometer",
        name: "Sick Face",
        unicode: "🤒",
        keywords: ["ill", "fever"],
      },
      {
        id: "facewithheadbandage",
        name: "Injured Face",
        unicode: "🤕",
        keywords: ["hurt", "bandage"],
      },
      {
        id: "nauseatedface",
        name: "Nauseated Face",
        unicode: "🤢",
        keywords: ["sick", "gross"],
      },
      {
        id: "vomitingface",
        name: "Vomiting Face",
        unicode: "🤮",
        keywords: ["sick", "gross"],
      },
      {
        id: "thinking",
        name: "Thinking Face",
        unicode: "🤔",
        keywords: ["think", "wonder"],
      },
      {
        id: "raisedeyebrow",
        name: "Raised Eyebrow",
        unicode: "🤨",
        keywords: ["doubt", "suspicious"],
      },
      {
        id: "eyeroll",
        name: "Face with Rolling Eyes",
        unicode: "🙄",
        keywords: ["boring", "sarcasm"],
      },
      {
        id: "persevere",
        name: "Persevering Face",
        unicode: "😣",
        keywords: ["struggling", "determined"],
      },
      {
        id: "sadbutrelievedface",
        name: "Sad But Relieved Face",
        unicode: "😥",
        keywords: ["sad", "hurt"],
      },
      {
        id: "cryingface",
        name: "Crying Face",
        unicode: "😢",
        keywords: ["sad", "tear"],
      },
      {
        id: "sob",
        name: "Loudly Crying Face",
        unicode: "😭",
        keywords: ["sad", "cry"],
      },
      {
        id: "scream",
        name: "Face Screaming in Fear",
        unicode: "😱",
        keywords: ["scared", "shock"],
      },
      {
        id: "confounded",
        name: "Confounded Face",
        unicode: "😖",
        keywords: ["sad", "confused"],
      },
      {
        id: "disappointed",
        name: "Disappointed Face",
        unicode: "😞",
        keywords: ["sad", "upset"],
      },
      {
        id: "sweat",
        name: "Downcast Face with Sweat",
        unicode: "😓",
        keywords: ["sad", "sweat"],
      },
      {
        id: "weary",
        name: "Weary Face",
        unicode: "😩",
        keywords: ["tired", "exhausted"],
      },
      {
        id: "tiredface",
        name: "Tired Face",
        unicode: "😫",
        keywords: ["frustrated", "tired"],
      },
      {
        id: "yawningface",
        name: "Yawning Face",
        unicode: "🥱",
        keywords: ["tired", "sleepy"],
      },
      {
        id: "triumph",
        name: "Face with Steam from Nose",
        unicode: "😤",
        keywords: ["angry", "frustrated"],
      },
      {
        id: "angry",
        name: "Pouting Face",
        unicode: "😡",
        keywords: ["angry", "upset"],
      },
      {
        id: "rage",
        name: "Angry Face",
        unicode: "😠",
        keywords: ["angry", "mean"],
      },
      {
        id: "cursing",
        name: "Cursing Face",
        unicode: "🤬",
        keywords: ["swear", "angry"],
      },
      {
        id: "smilingimp",
        name: "Smiling Imp",
        unicode: "😈",
        keywords: ["devil", "evil"],
      },
      { id: "imp", name: "Imp", unicode: "👿", keywords: ["devil", "evil"] },
      {
        id: "skull",
        name: "Skull",
        unicode: "💀",
        keywords: ["death", "scary"],
      },
      {
        id: "skullandcrossbones",
        name: "Skull and Crossbones",
        unicode: "☠️",
        keywords: ["poison", "danger"],
      },
      {
        id: "poop",
        name: "Pile of Poop",
        unicode: "💩",
        keywords: ["poop", "funny"],
      },
      {
        id: "clownface",
        name: "Clown Face",
        unicode: "🤡",
        keywords: ["clown", "joke"],
      },
      {
        id: "japaneseogre",
        name: "Ogre",
        unicode: "👹",
        keywords: ["demon", "scary"],
      },
      {
        id: "japanesegoblin",
        name: "Goblin",
        unicode: "👺",
        keywords: ["demon", "scary"],
      },
      {
        id: "ghost",
        name: "Ghost",
        unicode: "👻",
        keywords: ["scary", "halloween"],
      },
      { id: "alien", name: "Alien", unicode: "👽", keywords: ["space", "ufo"] },
      {
        id: "spaceinvader",
        name: "Alien Monster",
        unicode: "👾",
        keywords: ["space", "game"],
      },
      {
        id: "robot",
        name: "Robot",
        unicode: "🤖",
        keywords: ["machine", "tech"],
      },
      {
        id: "smileycat",
        name: "Grinning Cat",
        unicode: "😺",
        keywords: ["cat", "happy"],
      },
      {
        id: "smilecat",
        name: "Smiling Cat",
        unicode: "😸",
        keywords: ["cat", "happy"],
      },
      {
        id: "joycat",
        name: "Cat with Tears of Joy",
        unicode: "😹",
        keywords: ["cat", "laugh"],
      },
      {
        id: "hearteyescat",
        name: "Smiling Cat with Heart Eyes",
        unicode: "😻",
        keywords: ["cat", "love"],
      },
      {
        id: "smirkcat",
        name: "Cat with Wry Smile",
        unicode: "😼",
        keywords: ["cat", "sarcasm"],
      },
      {
        id: "kissingcat",
        name: "Kissing Cat",
        unicode: "😽",
        keywords: ["cat", "kiss"],
      },
      {
        id: "wearycat",
        name: "Weary Cat",
        unicode: "🙀",
        keywords: ["cat", "tired"],
      },
      {
        id: "cryingcatface",
        name: "Crying Cat",
        unicode: "😿",
        keywords: ["cat", "sad"],
      },
      {
        id: "poutingcat",
        name: "Pouting Cat",
        unicode: "😾",
        keywords: ["cat", "angry"],
      },
    ],
  },
  {
    name: "Gestures",
    items: [
      {
        id: "wave",
        name: "Waving Hand",
        unicode: "👋",
        keywords: ["hello", "hi", "wave"],
      },
      {
        id: "thumbs-up",
        name: "Thumbs Up",
        unicode: "👍",
        keywords: ["like", "yes", "good"],
      },
      {
        id: "clap",
        name: "Clapping",
        unicode: "👏",
        keywords: ["applause", "clap"],
      },
      {
        id: "pray",
        name: "Prayer",
        unicode: "🙏",
        keywords: ["thanks", "pray"],
      },
      {
        id: "fire",
        name: "Fire",
        unicode: "🔥",
        keywords: ["hot", "fire", "lit"],
      },
      {
        id: "peace",
        name: "Victory Hand",
        unicode: "✌️",
        keywords: ["peace", "victory"],
      },
      {
        id: "fist",
        name: "Raised Fist",
        unicode: "✊",
        keywords: ["power", "fist"],
      },
      {
        id: "handshake",
        name: "Handshake",
        unicode: "🤝",
        keywords: ["agreement", "meeting"],
      },
      {
        id: "crossedfingers",
        name: "Crossed Fingers",
        unicode: "🤞",
        keywords: ["hope", "luck"],
      },
      {
        id: "vulcan",
        name: "Vulcan Salute",
        unicode: "🖖",
        keywords: ["star trek", "vulcan"],
      },
      {
        id: "okhand",
        name: "OK Hand",
        unicode: "👌",
        keywords: ["okay", "perfect"],
      },
      {
        id: "callme",
        name: "Call Me Hand",
        unicode: "🤙",
        keywords: ["call", "phone"],
      },
      {
        id: "pointup",
        name: "Index Pointing Up",
        unicode: "☝️",
        keywords: ["one", "point"],
      },
      {
        id: "pointdown",
        name: "Index Pointing Down",
        unicode: "👇",
        keywords: ["point", "down"],
      },
      {
        id: "pointright",
        name: "Index Pointing Right",
        unicode: "👉",
        keywords: ["point", "right"],
      },
      {
        id: "pointleft",
        name: "Index Pointing Left",
        unicode: "👈",
        keywords: ["point", "left"],
      },
      {
        id: "raisedhand",
        name: "Raised Hand",
        unicode: "✋",
        keywords: ["stop", "raised"],
      },
      {
        id: "clappinghands",
        name: "Clapping Hands",
        unicode: "👏",
        keywords: ["clap", "applause"],
      },
    ],
  },
  {
    name: "Animals",
    items: [
      {
        id: "dog",
        name: "Dog Face",
        unicode: "🐶",
        keywords: ["animal", "dog", "pet"],
      },
      {
        id: "cat",
        name: "Cat Face",
        unicode: "🐱",
        keywords: ["animal", "cat", "pet"],
      },
      {
        id: "mouseface",
        name: "Mouse Face",
        unicode: "🐭",
        keywords: ["animal", "mouse", "mickey"],
      },
      {
        id: "hamster",
        name: "Hamster",
        unicode: "🐹",
        keywords: ["animal", "hamster"],
      },
      {
        id: "rabbitface",
        name: "Rabbit Face",
        unicode: "🐰",
        keywords: ["animal", "rabbit", "bunny"],
      },
      {
        id: "foxface",
        name: "Fox",
        unicode: "🦊",
        keywords: ["animal", "fox"],
      },
      {
        id: "bearface",
        name: "Bear Face",
        unicode: "🐻",
        keywords: ["animal", "bear"],
      },
      {
        id: "panda",
        name: "Panda",
        unicode: "🐼",
        keywords: ["animal", "panda"],
      },
      {
        id: "koala",
        name: "Koala",
        unicode: "🐨",
        keywords: ["animal", "koala"],
      },
      {
        id: "tigerface",
        name: "Tiger Face",
        unicode: "🐯",
        keywords: ["animal", "tiger"],
      },
      {
        id: "lion",
        name: "Lion",
        unicode: "🦁",
        keywords: ["animal", "lion", "brave"],
      },
      {
        id: "cowface",
        name: "Cow Face",
        unicode: "🐮",
        keywords: ["animal", "cow"],
      },
      {
        id: "pigface",
        name: "Pig Face",
        unicode: "🐷",
        keywords: ["animal", "pig"],
      },
      { id: "frog", name: "Frog", unicode: "🐸", keywords: ["animal", "frog"] },
      {
        id: "monkeyface",
        name: "Monkey Face",
        unicode: "🐵",
        keywords: ["animal", "monkey"],
      },
      {
        id: "chicken",
        name: "Chicken",
        unicode: "🐔",
        keywords: ["animal", "chicken"],
      },
      {
        id: "penguin",
        name: "Penguin",
        unicode: "🐧",
        keywords: ["animal", "penguin", "bird"],
      },
      { id: "bird", name: "Bird", unicode: "🐦", keywords: ["animal", "bird"] },
      {
        id: "babychick",
        name: "Baby Chick",
        unicode: "🐤",
        keywords: ["animal", "chick", "cute"],
      },
      {
        id: "hatchingchick",
        name: "Hatching Chick",
        unicode: "🐣",
        keywords: ["animal", "chick", "egg"],
      },
      { id: "duck", name: "Duck", unicode: "🦆", keywords: ["animal", "duck"] },
      {
        id: "eagle",
        name: "Eagle",
        unicode: "🦅",
        keywords: ["animal", "eagle", "bird"],
      },
      {
        id: "owl",
        name: "Owl",
        unicode: "🦉",
        keywords: ["animal", "owl", "wise"],
      },
      {
        id: "bat",
        name: "Bat",
        unicode: "🦇",
        keywords: ["animal", "bat", "night"],
      },
      {
        id: "wolf",
        name: "Wolf",
        unicode: "🐺",
        keywords: ["animal", "wolf", "wild"],
      },
      { id: "boar", name: "Boar", unicode: "🐗", keywords: ["animal", "boar"] },
      {
        id: "horseface",
        name: "Horse Face",
        unicode: "🐴",
        keywords: ["animal", "horse"],
      },
      {
        id: "unicorn",
        name: "Unicorn",
        unicode: "🦄",
        keywords: ["fantasy", "magic", "mythical"],
      },
      {
        id: "honeybee",
        name: "Honeybee",
        unicode: "🐝",
        keywords: ["animal", "bee", "insect"],
      },
      { id: "bug", name: "Bug", unicode: "🐛", keywords: ["animal", "insect"] },
      {
        id: "butterfly",
        name: "Butterfly",
        unicode: "🦋",
        keywords: ["animal", "insect", "butterfly"],
      },
      {
        id: "snail",
        name: "Snail",
        unicode: "🐌",
        keywords: ["animal", "snail", "slow"],
      },
      {
        id: "ladybug",
        name: "Lady Beetle",
        unicode: "🐞",
        keywords: ["animal", "insect", "ladybug"],
      },
      {
        id: "ant",
        name: "Ant",
        unicode: "🐜",
        keywords: ["animal", "insect", "ant"],
      },
      {
        id: "turtle",
        name: "Turtle",
        unicode: "🐢",
        keywords: ["animal", "turtle", "slow"],
      },
      {
        id: "snake",
        name: "Snake",
        unicode: "🐍",
        keywords: ["animal", "snake", "dangerous"],
      },
      {
        id: "horse",
        name: "Horse",
        unicode: "🐎",
        keywords: ["animal", "horse"],
      },
      {
        id: "octopus",
        name: "Octopus",
        unicode: "🐙",
        keywords: ["sea", "animal", "octopus"],
      },
      { id: "shell", name: "Shell", unicode: "🐚", keywords: ["sea", "beach"] },
      {
        id: "fish",
        name: "Fish",
        unicode: "🐟",
        keywords: ["sea", "animal", "fish"],
      },
      {
        id: "dolphin",
        name: "Dolphin",
        unicode: "🐬",
        keywords: ["sea", "animal", "dolphin"],
      },
      {
        id: "whale",
        name: "Whale",
        unicode: "🐳",
        keywords: ["sea", "animal", "whale", "big"],
      },
      {
        id: "whale2",
        name: "Whale",
        unicode: "🐋",
        keywords: ["sea", "animal", "whale"],
      },
      {
        id: "shark",
        name: "Shark",
        unicode: "🦈",
        keywords: ["animal", "shark", "danger"],
      },
      {
        id: "crocodile",
        name: "Crocodile",
        unicode: "🐊",
        keywords: ["animal", "crocodile", "danger"],
      },
      {
        id: "leopard",
        name: "Leopard",
        unicode: "🐆",
        keywords: ["animal", "leopard"],
      },
      {
        id: "zebra",
        name: "Zebra",
        unicode: "🦓",
        keywords: ["animal", "zebra"],
      },
      {
        id: "gorilla",
        name: "Gorilla",
        unicode: "🦍",
        keywords: ["animal", "gorilla", "strong"],
      },
      {
        id: "orangutan",
        name: "Orangutan",
        unicode: "🦧",
        keywords: ["animal", "orangutan"],
      },
      {
        id: "elephant",
        name: "Elephant",
        unicode: "🐘",
        keywords: ["animal", "elephant", "big"],
      },
      {
        id: "hippopotamus",
        name: "Hippopotamus",
        unicode: "🦛",
        keywords: ["animal", "hippo"],
      },
      {
        id: "rhinoceros",
        name: "Rhinoceros",
        unicode: "🦏",
        keywords: ["animal", "rhino"],
      },
      {
        id: "camel",
        name: "Camel",
        unicode: "🐫",
        keywords: ["animal", "camel", "desert"],
      },
      {
        id: "camel2",
        name: "Camel",
        unicode: "🐪",
        keywords: ["animal", "camel"],
      },
      {
        id: "giraffe",
        name: "Giraffe",
        unicode: "🦒",
        keywords: ["animal", "giraffe", "tall"],
      },
      {
        id: "kangaroo",
        name: "Kangaroo",
        unicode: "🦘",
        keywords: ["animal", "kangaroo"],
      },
      {
        id: "waterbuffalo",
        name: "Water Buffalo",
        unicode: "🦬",
        keywords: ["animal", "buffalo"],
      },
      { id: "ox", name: "Ox", unicode: "🐂", keywords: ["animal", "ox"] },
      { id: "cow", name: "Cow", unicode: "🐄", keywords: ["animal", "cow"] },
      { id: "pig", name: "Pig", unicode: "🐖", keywords: ["animal", "pig"] },
      { id: "ram", name: "Ram", unicode: "🐏", keywords: ["animal", "sheep"] },
      {
        id: "sheep",
        name: "Sheep",
        unicode: "🐑",
        keywords: ["animal", "sheep"],
      },
      {
        id: "deer",
        name: "Deer",
        unicode: "🦌",
        keywords: ["animal", "deer", "nature"],
      },
      { id: "goat", name: "Goat", unicode: "🐐", keywords: ["animal", "goat"] },
      {
        id: "poodle",
        name: "Poodle",
        unicode: "🐩",
        keywords: ["animal", "dog", "poodle"],
      },
      {
        id: "guidedog",
        name: "Guide Dog",
        unicode: "🦮",
        keywords: ["dog", "help", "assist"],
      },
      {
        id: "rooster",
        name: "Rooster",
        unicode: "🐓",
        keywords: ["animal", "rooster", "chicken"],
      },
      {
        id: "turkey",
        name: "Turkey",
        unicode: "🦃",
        keywords: ["animal", "turkey", "thanksgiving"],
      },
      {
        id: "peacock",
        name: "Peacock",
        unicode: "🦚",
        keywords: ["animal", "bird", "peacock"],
      },
      {
        id: "parrot",
        name: "Parrot",
        unicode: "🦜",
        keywords: ["animal", "bird", "parrot"],
      },
      {
        id: "swan",
        name: "Swan",
        unicode: "🦢",
        keywords: ["animal", "bird", "swan", "elegant"],
      },
      {
        id: "cricket",
        name: "Cricket",
        unicode: "🦗",
        keywords: ["animal", "insect", "cricket"],
      },
      { id: "egg", name: "Egg", unicode: "🥚", keywords: ["food", "egg"] },
    ],
  },
  {
    name: "Food & Drink",
    items: [
      {
        id: "greenapple",
        name: "Green Apple",
        unicode: "🍏",
        keywords: ["fruit", "food", "apple"],
      },
      {
        id: "apple",
        name: "Red Apple",
        unicode: "🍎",
        keywords: ["fruit", "food", "apple"],
      },
      { id: "pear", name: "Pear", unicode: "🍐", keywords: ["fruit", "food"] },
      {
        id: "orange",
        name: "Orange",
        unicode: "🍊",
        keywords: ["fruit", "food", "orange"],
      },
      {
        id: "lemon",
        name: "Lemon",
        unicode: "🍋",
        keywords: ["fruit", "food", "lemon", "sour"],
      },
      {
        id: "banana",
        name: "Banana",
        unicode: "🍌",
        keywords: ["fruit", "food", "banana", "yellow"],
      },
      {
        id: "watermelon",
        name: "Watermelon",
        unicode: "🍉",
        keywords: ["fruit", "food", "watermelon", "summer"],
      },
      {
        id: "grapes",
        name: "Grapes",
        unicode: "🍇",
        keywords: ["fruit", "food", "grapes"],
      },
      {
        id: "strawberry",
        name: "Strawberry",
        unicode: "🍓",
        keywords: ["fruit", "food", "strawberry", "red"],
      },
      {
        id: "melon",
        name: "Melon",
        unicode: "🍈",
        keywords: ["fruit", "food", "melon"],
      },
      {
        id: "cherries",
        name: "Cherries",
        unicode: "🍒",
        keywords: ["fruit", "food", "cherries"],
      },
      {
        id: "peach",
        name: "Peach",
        unicode: "🍑",
        keywords: ["fruit", "food", "peach"],
      },
      {
        id: "mango",
        name: "Mango",
        unicode: "🥭",
        keywords: ["fruit", "food", "mango", "tropical"],
      },
      {
        id: "pineapple",
        name: "Pineapple",
        unicode: "🍍",
        keywords: ["fruit", "food", "pineapple", "tropical"],
      },
      {
        id: "coconut",
        name: "Coconut",
        unicode: "🥥",
        keywords: ["fruit", "food", "coconut", "tropical"],
      },
      {
        id: "kiwifruit",
        name: "Kiwi Fruit",
        unicode: "🥝",
        keywords: ["fruit", "food", "kiwi", "green"],
      },
      {
        id: "tomato",
        name: "Tomato",
        unicode: "🍅",
        keywords: ["vegetable", "food", "tomato", "red"],
      },
      {
        id: "eggplant",
        name: "Eggplant",
        unicode: "🍆",
        keywords: ["vegetable", "food", "eggplant", "purple"],
      },
      {
        id: "avocado",
        name: "Avocado",
        unicode: "🥑",
        keywords: ["vegetable", "food", "avocado", "green"],
      },
      {
        id: "broccoli",
        name: "Broccoli",
        unicode: "🥦",
        keywords: ["vegetable", "food", "broccoli", "green"],
      },
      {
        id: "leafygreen",
        name: "Leafy Green",
        unicode: "🥬",
        keywords: ["vegetable", "food", "green"],
      },
      {
        id: "cucumber",
        name: "Cucumber",
        unicode: "🥒",
        keywords: ["vegetable", "food", "cucumber", "green"],
      },
      {
        id: "hotpepper",
        name: "Hot Pepper",
        unicode: "🌶️",
        keywords: ["vegetable", "food", "pepper", "spicy", "red"],
      },
      {
        id: "corn",
        name: "Corn",
        unicode: "🌽",
        keywords: ["vegetable", "food", "corn", "yellow"],
      },
      {
        id: "carrot",
        name: "Carrot",
        unicode: "🥕",
        keywords: ["vegetable", "food", "carrot", "orange"],
      },
      {
        id: "garlic",
        name: "Garlic",
        unicode: "🧄",
        keywords: ["vegetable", "food", "garlic"],
      },
      {
        id: "onion",
        name: "Onion",
        unicode: "🧅",
        keywords: ["vegetable", "food", "onion"],
      },
      {
        id: "potato",
        name: "Potato",
        unicode: "🥔",
        keywords: ["vegetable", "food", "potato"],
      },
      {
        id: "sweetpotato",
        name: "Sweet Potato",
        unicode: "🍠",
        keywords: ["vegetable", "food", "potato"],
      },
      {
        id: "croissant",
        name: "Croissant",
        unicode: "🥐",
        keywords: ["bread", "food", "breakfast", "french"],
      },
      {
        id: "bagel",
        name: "Bagel",
        unicode: "🥯",
        keywords: ["bread", "food", "bagel"],
      },
      {
        id: "bread",
        name: "Bread",
        unicode: "🍞",
        keywords: ["bread", "food", "grain"],
      },
      {
        id: "baguettebread",
        name: "Baguette Bread",
        unicode: "🥖",
        keywords: ["bread", "food", "french"],
      },
      {
        id: "pretzel",
        name: "Pretzel",
        unicode: "🥨",
        keywords: ["bread", "food", "pretzel", "snack"],
      },
      {
        id: "cheese",
        name: "Cheese",
        unicode: "🧀",
        keywords: ["food", "cheese", "dairy"],
      },
      {
        id: "egg",
        name: "Egg",
        unicode: "🥚",
        keywords: ["food", "egg", "breakfast"],
      },
      {
        id: "cooking",
        name: "Cooking",
        unicode: "🍳",
        keywords: ["food", "fried", "egg"],
      },
      {
        id: "butter",
        name: "Butter",
        unicode: "🧈",
        keywords: ["food", "butter", "dairy"],
      },
      {
        id: "pancakes",
        name: "Pancakes",
        unicode: "🥞",
        keywords: ["food", "pancakes", "breakfast"],
      },
      {
        id: "bacon",
        name: "Bacon",
        unicode: "🥓",
        keywords: ["food", "bacon", "meat", "breakfast"],
      },
      {
        id: "poultryleg",
        name: "Poultry Leg",
        unicode: "🍗",
        keywords: ["food", "meat", "chicken"],
      },
      {
        id: "meatonbone",
        name: "Meat on Bone",
        unicode: "🍖",
        keywords: ["food", "meat"],
      },
      {
        id: "hotdog",
        name: "Hot Dog",
        unicode: "🌭",
        keywords: ["food", "hotdog", "sausage"],
      },
      {
        id: "hamburger",
        name: "Hamburger",
        unicode: "🍔",
        keywords: ["food", "hamburger", "burger", "meat"],
      },
      {
        id: "fries",
        name: "French Fries",
        unicode: "🍟",
        keywords: ["food", "fries", "fast food"],
      },
      {
        id: "pizza",
        name: "Pizza",
        unicode: "🍕",
        keywords: ["food", "pizza", "italian", "cheese"],
      },
      {
        id: "sandwich",
        name: "Sandwich",
        unicode: "🥪",
        keywords: ["food", "sandwich", "bread"],
      },
      {
        id: "stuffedflatbread",
        name: "Stuffed Flatbread",
        unicode: "🥙",
        keywords: ["food", "sandwich"],
      },
      {
        id: "falafel",
        name: "Falafel",
        unicode: "🧆",
        keywords: ["food", "falafel", "vegetarian"],
      },
      {
        id: "taco",
        name: "Taco",
        unicode: "🌮",
        keywords: ["food", "taco", "mexican"],
      },
      {
        id: "burrito",
        name: "Burrito",
        unicode: "🌯",
        keywords: ["food", "burrito", "mexican"],
      },
      {
        id: "greensalad",
        name: "Green Salad",
        unicode: "🥗",
        keywords: ["food", "salad", "vegetarian", "healthy"],
      },
      {
        id: "shallowpanoffood",
        name: "Shallow Pan of Food",
        unicode: "🥘",
        keywords: ["food", "cooking"],
      },
      {
        id: "cannedfood",
        name: "Canned Food",
        unicode: "🥫",
        keywords: ["food", "can"],
      },
      {
        id: "spaghetti",
        name: "Spaghetti",
        unicode: "🍝",
        keywords: ["food", "pasta", "italian"],
      },
      {
        id: "ramen",
        name: "Ramen",
        unicode: "🍜",
        keywords: ["food", "noodles", "ramen", "asian"],
      },
      {
        id: "popcorn",
        name: "Popcorn",
        unicode: "🍿",
        keywords: ["food", "snack", "movie"],
      },
      {
        id: "curryrice",
        name: "Curry Rice",
        unicode: "🍛",
        keywords: ["food", "curry", "asian", "spicy"],
      },
      {
        id: "sushi",
        name: "Sushi",
        unicode: "🍣",
        keywords: ["food", "sushi", "japanese", "seafood"],
      },
      {
        id: "bento",
        name: "Bento Box",
        unicode: "🍱",
        keywords: ["food", "bento", "japanese"],
      },
      {
        id: "dumpling",
        name: "Dumpling",
        unicode: "🥟",
        keywords: ["food", "dumpling", "asian"],
      },
      {
        id: "oyster",
        name: "Oyster",
        unicode: "🦪",
        keywords: ["food", "oyster", "seafood"],
      },
      {
        id: "friedshrimp",
        name: "Fried Shrimp",
        unicode: "🍤",
        keywords: ["food", "shrimp", "seafood"],
      },
      {
        id: "riceball",
        name: "Rice Ball",
        unicode: "🍙",
        keywords: ["food", "rice", "japanese"],
      },
      {
        id: "cookedrice",
        name: "Cooked Rice",
        unicode: "🍚",
        keywords: ["food", "rice", "grain"],
      },
      {
        id: "ricecracker",
        name: "Rice Cracker",
        unicode: "🍘",
        keywords: ["food", "rice", "snack"],
      },
      {
        id: "fishcakewithswirl",
        name: "Fish Cake with Swirl",
        unicode: "🍥",
        keywords: ["food", "cake", "fish"],
      },
      {
        id: "fortunecookie",
        name: "Fortune Cookie",
        unicode: "🥠",
        keywords: ["food", "cookie", "dessert", "lucky"],
      },
      {
        id: "mooncake",
        name: "Moon Cake",
        unicode: "🥮",
        keywords: ["food", "cake", "asian"],
      },
      {
        id: "oden",
        name: "Oden",
        unicode: "🍢",
        keywords: ["food", "asian", "skewer"],
      },
      {
        id: "dango",
        name: "Dango",
        unicode: "🍡",
        keywords: ["food", "dumpling", "japanese", "sweet"],
      },
      {
        id: "shavedice",
        name: "Shaved Ice",
        unicode: "🍧",
        keywords: ["food", "ice", "dessert", "cold"],
      },
      {
        id: "icecream",
        name: "Ice Cream",
        unicode: "🍨",
        keywords: ["food", "ice cream", "dessert", "cold", "sweet"],
      },
      {
        id: "softicecream",
        name: "Soft Ice Cream",
        unicode: "🍦",
        keywords: ["food", "ice cream", "dessert", "sweet"],
      },
      {
        id: "cake",
        name: "Cake",
        unicode: "🍰",
        keywords: ["food", "cake", "dessert", "sweet", "birthday"],
      },
      {
        id: "birthdaycake",
        name: "Birthday Cake",
        unicode: "🎂",
        keywords: ["food", "cake", "birthday", "celebration", "dessert"],
      },
      {
        id: "cupcake",
        name: "Cupcake",
        unicode: "🧁",
        keywords: ["food", "cupcake", "dessert", "sweet"],
      },
      {
        id: "custard",
        name: "Custard",
        unicode: "🍮",
        keywords: ["food", "custard", "dessert", "sweet"],
      },
      {
        id: "lollipop",
        name: "Lollipop",
        unicode: "🍭",
        keywords: ["food", "lollipop", "candy", "sweet"],
      },
      {
        id: "candy",
        name: "Candy",
        unicode: "🍬",
        keywords: ["food", "candy", "sweet"],
      },
      {
        id: "chocolatebar",
        name: "Chocolate Bar",
        unicode: "🍫",
        keywords: ["food", "chocolate", "sweet", "dessert"],
      },
      {
        id: "popcorn",
        name: "Popcorn",
        unicode: "🍿",
        keywords: ["food", "popcorn", "snack", "movie"],
      },
      {
        id: "doughnut",
        name: "Doughnut",
        unicode: "🍩",
        keywords: ["food", "donut", "sweet", "dessert"],
      },
      {
        id: "cookie",
        name: "Cookie",
        unicode: "🍪",
        keywords: ["food", "cookie", "sweet", "dessert"],
      },
      {
        id: "chestnut",
        name: "Chestnut",
        unicode: "🌰",
        keywords: ["food", "nut"],
      },
      {
        id: "honeypot",
        name: "Honey Pot",
        unicode: "🍯",
        keywords: ["food", "honey", "sweet"],
      },
      {
        id: "glassofmilk",
        name: "Glass of Milk",
        unicode: "🥛",
        keywords: ["food", "milk", "drink", "dairy", "white"],
      },
      {
        id: "babybottle",
        name: "Baby Bottle",
        unicode: "🍼",
        keywords: ["food", "bottle", "drink", "baby"],
      },
      {
        id: "coffee",
        name: "Coffee",
        unicode: "☕",
        keywords: ["drink", "coffee", "hot", "morning", "brown"],
      },
      {
        id: "tea",
        name: "Tea",
        unicode: "🍵",
        keywords: ["drink", "tea", "hot", "beverage"],
      },
      {
        id: "sake",
        name: "Sake",
        unicode: "🍶",
        keywords: ["drink", "sake", "alcohol", "japanese"],
      },
      {
        id: "bottlewithpoppingcork",
        name: "Bottle with Popping Cork",
        unicode: "🍾",
        keywords: ["drink", "alcohol", "champagne", "celebration"],
      },
      {
        id: "wineglass",
        name: "Wine Glass",
        unicode: "🍷",
        keywords: ["drink", "wine", "alcohol", "red"],
      },
      {
        id: "cocktailglass",
        name: "Cocktail Glass",
        unicode: "🍸",
        keywords: ["drink", "cocktail", "alcohol"],
      },
      {
        id: "tropicaldrink",
        name: "Tropical Drink",
        unicode: "🍹",
        keywords: ["drink", "tropical", "vacation", "colorful"],
      },
      {
        id: "beermug",
        name: "Beer Mug",
        unicode: "🍺",
        keywords: ["drink", "beer", "alcohol", "golden"],
      },
      {
        id: "clinkingbeermugs",
        name: "Clinking Beer Mugs",
        unicode: "🍻",
        keywords: ["drink", "beer", "toast", "celebration"],
      },
      {
        id: "clinkingglasses",
        name: "Clinking Glasses",
        unicode: "🥂",
        keywords: ["drink", "champagne", "celebration", "toast"],
      },
      {
        id: "tumblerglass",
        name: "Tumbler Glass",
        unicode: "🥃",
        keywords: ["drink", "glass"],
      },
      {
        id: "cupwithstraw",
        name: "Cup with Straw",
        unicode: "🥤",
        keywords: ["drink", "beverage"],
      },
    ],
  },
  {
    name: "Sports",
    items: [
      {
        id: "soccer",
        name: "Soccer Ball",
        unicode: "⚽",
        keywords: ["sports", "soccer", "football", "ball"],
      },
      {
        id: "basketball",
        name: "Basketball",
        unicode: "🏀",
        keywords: ["sports", "basketball", "ball"],
      },
      {
        id: "americanfootball",
        name: "American Football",
        unicode: "🏈",
        keywords: ["sports", "football", "ball"],
      },
      {
        id: "baseball",
        name: "Baseball",
        unicode: "⚾",
        keywords: ["sports", "baseball", "ball"],
      },
      {
        id: "softball",
        name: "Softball",
        unicode: "🥎",
        keywords: ["sports", "softball", "ball"],
      },
      {
        id: "tennis",
        name: "Tennis",
        unicode: "🎾",
        keywords: ["sports", "tennis", "ball"],
      },
      {
        id: "volleyball",
        name: "Volleyball",
        unicode: "🏐",
        keywords: ["sports", "volleyball", "ball"],
      },
      {
        id: "rugbyfootball",
        name: "Rugby Football",
        unicode: "🏉",
        keywords: ["sports", "rugby", "ball"],
      },
      {
        id: "cricketgame",
        name: "Cricket Game",
        unicode: "🏏",
        keywords: ["sports", "cricket", "bat"],
      },
      {
        id: "bowling",
        name: "Bowling",
        unicode: "🎳",
        keywords: ["sports", "bowling", "pins"],
      },
      {
        id: "pingpong",
        name: "Ping Pong",
        unicode: "🏓",
        keywords: ["sports", "ping pong", "table tennis"],
      },
      {
        id: "badminton",
        name: "Badminton",
        unicode: "🏸",
        keywords: ["sports", "badminton", "racket"],
      },
      {
        id: "icehockey",
        name: "Ice Hockey",
        unicode: "🏒",
        keywords: ["sports", "hockey", "ice"],
      },
      {
        id: "fieldhockey",
        name: "Field Hockey",
        unicode: "🏑",
        keywords: ["sports", "hockey", "field"],
      },
      {
        id: "lacrosse",
        name: "Lacrosse",
        unicode: "🥍",
        keywords: ["sports", "lacrosse", "stick"],
      },
      {
        id: "golf",
        name: "Golf",
        unicode: "⛳",
        keywords: ["sports", "golf", "flag", "hole"],
      },
      {
        id: "iceskate",
        name: "Ice Skate",
        unicode: "⛸️",
        keywords: ["sports", "ice skating", "winter"],
      },
      {
        id: "fishingpoleandfish",
        name: "Fishing Pole and Fish",
        unicode: "🎣",
        keywords: ["sports", "fishing", "hobby"],
      },
      {
        id: "runningshirtwithsash",
        name: "Running Shirt",
        unicode: "🎽",
        keywords: ["sports", "running", "shirt"],
      },
      {
        id: "skis",
        name: "Skis",
        unicode: "🎿",
        keywords: ["sports", "skiing", "winter", "snow"],
      },
      {
        id: "skier",
        name: "Skier",
        unicode: "⛷️",
        keywords: ["sports", "skiing", "winter"],
      },
      {
        id: "snowboarder",
        name: "Snowboarder",
        unicode: "🏂",
        keywords: ["sports", "snowboarding", "winter", "snow"],
      },
      {
        id: "parachute",
        name: "Parachute",
        unicode: "🪂",
        keywords: ["sports", "parachute", "extreme", "sky"],
      },
      {
        id: "rollerskate",
        name: "Roller Skate",
        unicode: "🛼",
        keywords: ["sports", "roller skate", "retro"],
      },
      {
        id: "skateboard",
        name: "Skateboard",
        unicode: "🛹",
        keywords: ["sports", "skateboard", "extreme"],
      },
      {
        id: "weightlifter",
        name: "Weight Lifter",
        unicode: "🏋️",
        keywords: ["sports", "weightlifting", "gym", "strong"],
      },
      {
        id: "swimmer",
        name: "Swimmer",
        unicode: "🏊",
        keywords: ["sports", "swimming", "water"],
      },
      {
        id: "waterpolo",
        name: "Water Polo",
        unicode: "🤽",
        keywords: ["sports", "water polo", "water"],
      },
      {
        id: "rowingperson",
        name: "Rowing Person",
        unicode: "🚣",
        keywords: ["sports", "rowing", "boat", "water"],
      },
      {
        id: "climbingperson",
        name: "Climbing Person",
        unicode: "🧗",
        keywords: ["sports", "climbing", "rock", "extreme"],
      },
      {
        id: "personbiking",
        name: "Person Biking",
        unicode: "🚴",
        keywords: ["sports", "biking", "cycling"],
      },
      {
        id: "personmountainbiking",
        name: "Person Mountain Biking",
        unicode: "🚵",
        keywords: ["sports", "mountain biking", "extreme"],
      },
      // Add remaining sports emojis...
    ],
  },
  {
    name: "Symbols",
    items: [
      {
        id: "star",
        name: "Star",
        unicode: "⭐",
        keywords: ["star", "sparkle", "night", "magic", "wish"],
      },
      {
        id: "glowingstar",
        name: "Glowing Star",
        unicode: "🌟",
        keywords: ["star", "sparkle", "bright", "magic"],
      },
      {
        id: "sparkles",
        name: "Sparkles",
        unicode: "✨",
        keywords: ["sparkle", "magic", "shine", "glitter", "celebration"],
      },
      {
        id: "zap",
        name: "Lightning",
        unicode: "⚡",
        keywords: ["lightning", "electricity", "fast", "power"],
      },
      {
        id: "comet",
        name: "Comet",
        unicode: "☄️",
        keywords: ["comet", "space", "meteor"],
      },
      {
        id: "explosion",
        name: "Explosion",
        unicode: "💥",
        keywords: ["explosion", "boom", "energy", "pow"],
      },
      {
        id: "fire",
        name: "Fire",
        unicode: "🔥",
        keywords: ["fire", "hot", "flame", "danger", "lit"],
      },
      {
        id: "rainbow",
        name: "Rainbow",
        unicode: "🌈",
        keywords: ["rainbow", "colorful", "beautiful", "sky", "hope"],
      },
      // Add all remaining symbols...
    ],
  },
  {
    name: "Party & Festive",
    items: [
      {
        id: "partypopper",
        name: "Party Popper",
        unicode: "🎉",
        keywords: ["party", "celebration", "birthday", "confetti", "fun"],
      },
      {
        id: "confettiball",
        name: "Confetti Ball",
        unicode: "🎊",
        keywords: ["party", "celebration", "birthday", "confetti"],
      },
      {
        id: "balloon",
        name: "Balloon",
        unicode: "🎈",
        keywords: ["party", "birthday", "celebration", "colorful"],
      },
      {
        id: "gift",
        name: "Wrapped Gift",
        unicode: "🎁",
        keywords: ["party", "gift", "birthday", "present", "celebration"],
      },
      {
        id: "ribbon",
        name: "Ribbon",
        unicode: "🎀",
        keywords: ["party", "gift", "bow", "celebration"],
      },
      {
        id: "birthdaycake",
        name: "Birthday Cake",
        unicode: "🎂",
        keywords: ["birthday", "cake", "celebration", "party", "dessert"],
      },
      {
        id: "jackolantern",
        name: "Jack-o-Lantern",
        unicode: "🎃",
        keywords: ["halloween", "pumpkin", "scary", "celebration"],
      },
      {
        id: "christmastree",
        name: "Christmas Tree",
        unicode: "🎄",
        keywords: ["christmas", "holiday", "tree", "winter", "celebration"],
      },
      {
        id: "fireworks",
        name: "Fireworks",
        unicode: "🎆",
        keywords: ["celebration", "fireworks", "party", "night"],
      },
      {
        id: "sparkler",
        name: "Sparkler",
        unicode: "🎇",
        keywords: ["celebration", "fireworks", "sparkle", "light"],
      },
      {
        id: "partyingface",
        name: "Partying Face",
        unicode: "🥳",
        keywords: ["party", "celebration", "birthday", "happy", "fun"],
      },
      {
        id: "sparkles",
        name: "Sparkles",
        unicode: "✨",
        keywords: ["celebration", "magic", "sparkle", "shine", "glitter"],
      },
      {
        id: "firecracker",
        name: "Firecracker",
        unicode: "🧨",
        keywords: ["celebration", "new year", "festival", "fireworks"],
      },
      {
        id: "tada",
        name: "Tada",
        unicode: "🎉",
        keywords: ["party", "confetti", "celebration", "fun"],
      },
      {
        id: "confetti",
        name: "Confetti",
        unicode: "🎊",
        keywords: ["party", "celebration", "confetti"],
      },
      {
        id: "balloons",
        name: "Balloons",
        unicode: "🎈",
        keywords: ["party", "colorful", "celebration"],
      },
      {
        id: "newyear",
        name: "New Year",
        unicode: "🥂",
        keywords: ["celebration", "toast", "new year", "party"],
      },
      {
        id: "candles",
        name: "Candle",
        unicode: "🕯️",
        keywords: ["celebration", "memorial", "festive"],
      },
      {
        id: "menorah",
        name: "Menorah",
        unicode: "🕎",
        keywords: ["hanukkah", "holiday", "festival"],
      },
      {
        id: "clinkingglasses",
        name: "Clinking Glasses",
        unicode: "🥂",
        keywords: ["celebration", "toast", "party", "drink"],
      },
      {
        id: "champagne",
        name: "Bottle with Popping Cork",
        unicode: "🍾",
        keywords: ["celebration", "champagne", "party", "drink"],
      },
      {
        id: "holly",
        name: "Holly",
        unicode: "🍂",
        keywords: ["christmas", "holiday", "decked halls", "winter"],
      },
      {
        id: "snowflake",
        name: "Snowflake",
        unicode: "❄️",
        keywords: ["winter", "christmas", "cold", "holiday"],
      },
      {
        id: "bell",
        name: "Bell",
        unicode: "🔔",
        keywords: ["holiday", "christmas", "notification"],
      },
      {
        id: "trophy",
        name: "Trophy",
        unicode: "🏆",
        keywords: ["award", "celebrate", "win"],
      },
      {
        id: "medal",
        name: "Medal",
        unicode: "🏅",
        keywords: ["award", "achievement", "celebrate"],
      },
      {
        id: "ribbonmedal",
        name: "Ribbon Medal",
        unicode: "🎗️",
        keywords: ["award", "achievement", "remembrance"],
      },
    ],
  },

  {
    name: "Disney",
    items: [
      {
        id: "Vector",
        name: "Vector",
        path: "/svg/Disney/Vector.svg",
        keywords: ["Disney"],
      },
      {
        id: "anna",
        name: "anna",
        path: "/svg/Disney/anna.svg",
        keywords: ["Disney"],
      },
      {
        id: "buz",
        name: "buz",
        path: "/svg/Disney/buz.svg",
        keywords: ["Disney"],
      },
      {
        id: "elsa",
        name: "elsa",
        path: "/svg/Disney/elsa.svg",
        keywords: ["Disney"],
      },
      {
        id: "jasmine",
        name: "jasmine",
        path: "/svg/Disney/jasmine.svg",
        keywords: ["Disney"],
      },
      {
        id: "jenie",
        name: "jenie",
        path: "/svg/Disney/jenie.svg",
        keywords: ["Disney"],
      },
      {
        id: "kris",
        name: "kris",
        path: "/svg/Disney/kris.svg",
        keywords: ["Disney"],
      },
      {
        id: "mickymouse",
        name: "mickymouse",
        path: "/svg/Disney/mickymouse.svg",
        keywords: ["Disney"],
      },
      {
        id: "olaf",
        name: "olaf",
        path: "/svg/Disney/olaf.svg",
        keywords: ["Disney"],
      },
      {
        id: "paperina",
        name: "paperina",
        path: "/svg/Disney/paperina.svg",
        keywords: ["Disney"],
      },
      {
        id: "paperino",
        name: "paperino",
        path: "/svg/Disney/paperino.svg",
        keywords: ["Disney"],
      },
      {
        id: "pluto",
        name: "pluto",
        path: "/svg/Disney/pluto.svg",
        keywords: ["Disney"],
      },
      {
        id: "simba",
        name: "simba",
        path: "/svg/Disney/simba.svg",
        keywords: ["Disney"],
      },
      {
        id: "stich1",
        name: "stich1",
        path: "/svg/Disney/stich1.svg",
        keywords: ["Disney"],
      },
      {
        id: "stich2",
        name: "stich2",
        path: "/svg/Disney/stich2.svg",
        keywords: ["Disney"],
      },
      {
        id: "sully",
        name: "sully",
        path: "/svg/Disney/sully.svg",
        keywords: ["Disney"],
      },
      {
        id: "sven",
        name: "sven",
        path: "/svg/Disney/sven.svg",
        keywords: ["Disney"],
      },
      {
        id: "toy1",
        name: "toy1",
        path: "/svg/Disney/toy1.svg",
        keywords: ["Disney"],
      },
    ],
  },
  {
    name: "Minecraft",
    items: [
      {
        id: "Group 1",
        name: "Group 1",
        path: "/svg/Minecraft/Group 1.svg",
        keywords: ["Minecraft"],
      },
      {
        id: "Group 10",
        name: "Group 10",
        path: "/svg/Minecraft/Group 10.svg",
        keywords: ["Minecraft"],
      },
      {
        id: "Group 11",
        name: "Group 11",
        path: "/svg/Minecraft/Group 11.svg",
        keywords: ["Minecraft"],
      },
      {
        id: "Group 12",
        name: "Group 12",
        path: "/svg/Minecraft/Group 12.svg",
        keywords: ["Minecraft"],
      },
      {
        id: "Group 2",
        name: "Group 2",
        path: "/svg/Minecraft/Group 2.svg",
        keywords: ["Minecraft"],
      },
      {
        id: "Group 3",
        name: "Group 3",
        path: "/svg/Minecraft/Group 3.svg",
        keywords: ["Minecraft"],
      },
      {
        id: "Group 4",
        name: "Group 4",
        path: "/svg/Minecraft/Group 4.svg",
        keywords: ["Minecraft"],
      },
      {
        id: "Group 5",
        name: "Group 5",
        path: "/svg/Minecraft/Group 5.svg",
        keywords: ["Minecraft"],
      },
      {
        id: "Group 6",
        name: "Group 6",
        path: "/svg/Minecraft/Group 6.svg",
        keywords: ["Minecraft"],
      },
      {
        id: "Group 7",
        name: "Group 7",
        path: "/svg/Minecraft/Group 7.svg",
        keywords: ["Minecraft"],
      },
      {
        id: "Group 8",
        name: "Group 8",
        path: "/svg/Minecraft/Group 8.svg",
        keywords: ["Minecraft"],
      },
      {
        id: "Group 9",
        name: "Group 9",
        path: "/svg/Minecraft/Group 9.svg",
        keywords: ["Minecraft"],
      },
    ],
  },
  {
    name: "Superheroes",
    items: [
      {
        id: "antman",
        name: "antman",
        path: "/svg/Superheroes/antman.svg",
        keywords: ["Superheroes"],
      },
      {
        id: "black",
        name: "black",
        path: "/svg/Superheroes/black.svg",
        keywords: ["Superheroes"],
      },
      {
        id: "cap",
        name: "cap",
        path: "/svg/Superheroes/cap.svg",
        keywords: ["Superheroes"],
      },
      {
        id: "dog",
        name: "dog",
        path: "/svg/Superheroes/dog.svg",
        keywords: ["Superheroes"],
      },
      {
        id: "groot",
        name: "groot",
        path: "/svg/Superheroes/groot.svg",
        keywords: ["Superheroes"],
      },
      {
        id: "hulk",
        name: "hulk",
        path: "/svg/Superheroes/hulk.svg",
        keywords: ["Superheroes"],
      },
      {
        id: "ironman",
        name: "ironman",
        path: "/svg/Superheroes/ironman.svg",
        keywords: ["Superheroes"],
      },
      {
        id: "shield",
        name: "shield",
        path: "/svg/Superheroes/shield.svg",
        keywords: ["Superheroes"],
      },
      {
        id: "spiderman",
        name: "spiderman",
        path: "/svg/Superheroes/spiderman.svg",
        keywords: ["Superheroes"],
      },
      {
        id: "thor",
        name: "thor",
        path: "/svg/Superheroes/thor.svg",
        keywords: ["Superheroes"],
      },
      {
        id: "vision",
        name: "vision",
        path: "/svg/Superheroes/vision.svg",
        keywords: ["Superheroes"],
      },
    ],
  },
];
