// lib/emojis.ts
export interface EmojiData {
  unicode: string;
  shortcode: string;
  name: string;
  keywords: string[];
}

export const EMOJI_DATABASE: EmojiData[] = [
  // Smileys & Emotions
  {
    unicode: "😀",
    shortcode: ":grinning:",
    name: "Grinning Face",
    keywords: ["happy", "smile", "face"],
  },
  {
    unicode: "😃",
    shortcode: ":smiley:",
    name: "Grinning Face with Big Eyes",
    keywords: ["happy", "smile", "joy"],
  },
  {
    unicode: "😄",
    shortcode: ":smile:",
    name: "Grinning Face with Smiling Eyes",
    keywords: ["happy", "smile", "joy"],
  },
  {
    unicode: "😁",
    shortcode: ":grin:",
    name: "Beaming Face with Smiling Eyes",
    keywords: ["happy", "smile"],
  },
  {
    unicode: "😆",
    shortcode: ":laughing:",
    name: "Grinning Squinting Face",
    keywords: ["happy", "laugh", "joy"],
  },
  {
    unicode: "😅",
    shortcode: ":sweat_smile:",
    name: "Grinning Face with Sweat",
    keywords: ["happy", "laugh"],
  },
  {
    unicode: "🤣",
    shortcode: ":rofl:",
    name: "Rolling on the Floor Laughing",
    keywords: ["laugh", "happy"],
  },
  {
    unicode: "😂",
    shortcode: ":joy:",
    name: "Face with Tears of Joy",
    keywords: ["laugh", "happy", "cry"],
  },
  {
    unicode: "🙂",
    shortcode: ":slightly_smiling_face:",
    name: "Slightly Smiling Face",
    keywords: ["happy", "smile"],
  },
  {
    unicode: "🙃",
    shortcode: ":upside_down_face:",
    name: "Upside Down Face",
    keywords: ["sarcasm", "funny"],
  },
  {
    unicode: "😉",
    shortcode: ":wink:",
    name: "Winking Face",
    keywords: ["flirt", "happy"],
  },
  {
    unicode: "😊",
    shortcode: ":blush:",
    name: "Smiling Face with Smiling Eyes",
    keywords: ["happy", "kind"],
  },
  {
    unicode: "😇",
    shortcode: ":innocent:",
    name: "Smiling Face with Halo",
    keywords: ["angel", "good"],
  },
  {
    unicode: "🥰",
    shortcode: ":heart_eyes:",
    name: "Smiling Face with Heart Eyes",
    keywords: ["love", "heart"],
  },
  {
    unicode: "😍",
    shortcode: ":heart_eyes:",
    name: "Heart Eyes",
    keywords: ["love", "heart"],
  },
  {
    unicode: "🤩",
    shortcode: ":star_struck:",
    name: "Smiling Face with Star Eyes",
    keywords: ["star", "wow"],
  },
  {
    unicode: "😘",
    shortcode: ":kissing_heart:",
    name: "Face Blowing a Kiss",
    keywords: ["love", "kiss"],
  },
  {
    unicode: "😗",
    shortcode: ":kissing:",
    name: "Kissing Face",
    keywords: ["kiss", "love"],
  },
  {
    unicode: "😚",
    shortcode: ":kissing_closed_eyes:",
    name: "Kissing Face with Closed Eyes",
    keywords: ["kiss", "love"],
  },
  {
    unicode: "😙",
    shortcode: ":kissing_smiling_eyes:",
    name: "Kissing Face with Smiling Eyes",
    keywords: ["kiss", "love"],
  },
  {
    unicode: "🥲",
    shortcode: ":smiling_face_with_tear:",
    name: "Smiling Face with Tear",
    keywords: ["happy", "tear"],
  },
  {
    unicode: "😋",
    shortcode: ":yum:",
    name: "Face Savoring Food",
    keywords: ["tasty", "delicious"],
  },
  {
    unicode: "😛",
    shortcode: ":stuck_out_tongue:",
    name: "Tongue Out",
    keywords: ["playful", "silly"],
  },
  {
    unicode: "😜",
    shortcode: ":stuck_out_tongue_winking_eye:",
    name: "Winking with Tongue",
    keywords: ["playful", "silly"],
  },
  {
    unicode: "🤪",
    shortcode: ":zany_face:",
    name: "Zany Face",
    keywords: ["crazy", "playful"],
  },
  {
    unicode: "😌",
    shortcode: ":relieved:",
    name: "Relieved Face",
    keywords: ["calm", "peaceful"],
  },
  {
    unicode: "😔",
    shortcode: ":pensive:",
    name: "Pensive Face",
    keywords: ["sad", "thinking"],
  },
  {
    unicode: "😑",
    shortcode: ":expressionless:",
    name: "Expressionless Face",
    keywords: ["flat", "unimpressed"],
  },
  {
    unicode: "😐",
    shortcode: ":neutral_face:",
    name: "Neutral Face",
    keywords: ["meh", "no emotion"],
  },
  {
    unicode: "😶",
    shortcode: ":no_mouth:",
    name: "Face Without Mouth",
    keywords: ["silence", "secret"],
  },
  {
    unicode: "😏",
    shortcode: ":smirk:",
    name: "Smirking Face",
    keywords: ["cocky", "sly"],
  },
  {
    unicode: "😒",
    shortcode: ":unamused:",
    name: "Unamused Face",
    keywords: ["unimpressed", "sarcasm"],
  },
  {
    unicode: "🙁",
    shortcode: ":frowning:",
    name: "Frowning Face",
    keywords: ["sad", "unhappy"],
  },
  {
    unicode: "😬",
    shortcode: ":grimacing:",
    name: "Grimacing Face",
    keywords: ["awkward", "uncomfortable"],
  },
  {
    unicode: "🤥",
    shortcode: ":lying_face:",
    name: "Lying Face",
    keywords: ["liar", "dishonest"],
  },
  {
    unicode: "😌",
    shortcode: ":relieved:",
    name: "Relieved Face",
    keywords: ["calm", "peaceful"],
  },
  {
    unicode: "😪",
    shortcode: ":sleepy:",
    name: "Sleepy Face",
    keywords: ["tired", "sleep"],
  },
  {
    unicode: "🤤",
    shortcode: ":drooling_face:",
    name: "Drooling Face",
    keywords: ["yum", "hungry"],
  },
  {
    unicode: "😴",
    shortcode: ":sleeping:",
    name: "Sleeping Face",
    keywords: ["sleep", "zzz"],
  },
  {
    unicode: "😷",
    shortcode: ":mask:",
    name: "Face with Medical Mask",
    keywords: ["sick", "health"],
  },
  {
    unicode: "🤒",
    shortcode: ":face_with_thermometer:",
    name: "Sick Face",
    keywords: ["ill", "fever"],
  },
  {
    unicode: "🤕",
    shortcode: ":face_with_head_bandage:",
    name: "Injured Face",
    keywords: ["hurt", "bandage"],
  },
  {
    unicode: "🤢",
    shortcode: ":nauseated_face:",
    name: "Nauseated Face",
    keywords: ["sick", "gross"],
  },
  {
    unicode: "🤮",
    shortcode: ":vomiting_face:",
    name: "Vomiting Face",
    keywords: ["sick", "gross"],
  },
  {
    unicode: "🤔",
    shortcode: ":thinking:",
    name: "Thinking Face",
    keywords: ["think", "wonder"],
  },
  {
    unicode: "🤨",
    shortcode: ":raised_eyebrow:",
    name: "Raised Eyebrow",
    keywords: ["doubt", "suspicious"],
  },
  {
    unicode: "😐",
    shortcode: ":neutral_face:",
    name: "Neutral Face",
    keywords: ["unimpressed"],
  },
  {
    unicode: "🙄",
    shortcode: ":eye_roll:",
    name: "Face with Rolling Eyes",
    keywords: ["boring", "sarcasm"],
  },
  {
    unicode: "😣",
    shortcode: ":persevere:",
    name: "Persevering Face",
    keywords: ["struggling", "determined"],
  },
  {
    unicode: "😥",
    shortcode: ":relieved:",
    name: "Sad Relieved Face",
    keywords: ["sad", "relief"],
  },
  {
    unicode: "😮",
    shortcode: ":open_mouth:",
    name: "Face with Open Mouth",
    keywords: ["surprise", "shocked"],
  },
  {
    unicode: "🤐",
    shortcode: ":zipper_mouth_face:",
    name: "Zipper Mouth Face",
    keywords: ["quiet", "secret"],
  },
  {
    unicode: "😯",
    shortcode: ":hushed:",
    name: "Hushed Face",
    keywords: ["surprise", "shock"],
  },
  {
    unicode: "😲",
    shortcode: ":flushed:",
    name: "Flushed Face",
    keywords: ["surprise", "shocked"],
  },
  {
    unicode: "😳",
    shortcode: ":flushed:",
    name: "Flushed Face",
    keywords: ["embarrassed"],
  },
  {
    unicode: "🥺",
    shortcode: ":pleading_face:",
    name: "Pleading Face",
    keywords: ["cute", "puppy"],
  },
  {
    unicode: "😦",
    shortcode: ":frowning_open_mouth:",
    name: "Frowning Open Mouth",
    keywords: ["sad", "upset"],
  },
  {
    unicode: "😧",
    shortcode: ":anguished:",
    name: "Anguished Face",
    keywords: ["worry", "pain"],
  },
  {
    unicode: "😨",
    shortcode: ":fearful:",
    name: "Fearful Face",
    keywords: ["scared", "shock"],
  },
  {
    unicode: "😰",
    shortcode: ":anxious_face_with_sweat:",
    name: "Anxious Face with Sweat",
    keywords: ["worried", "stress"],
  },
  {
    unicode: "😥",
    shortcode: ":sad_but_relieved_face:",
    name: "Sad But Relieved Face",
    keywords: ["sad", "hurt"],
  },
  {
    unicode: "😢",
    shortcode: ":crying_face:",
    name: "Crying Face",
    keywords: ["sad", "tear"],
  },
  {
    unicode: "😭",
    shortcode: ":sob:",
    name: "Loudly Crying Face",
    keywords: ["sad", "cry"],
  },
  {
    unicode: "😱",
    shortcode: ":scream:",
    name: "Face Screaming in Fear",
    keywords: ["scared", "shock"],
  },
  {
    unicode: "😖",
    shortcode: ":confounded:",
    name: "Confounded Face",
    keywords: ["sad", "confused"],
  },
  {
    unicode: "😣",
    shortcode: ":persevere:",
    name: "Persevering Face",
    keywords: ["struggling", "fighting"],
  },
  {
    unicode: "😞",
    shortcode: ":disappointed:",
    name: "Disappointed Face",
    keywords: ["sad", "upset"],
  },
  {
    unicode: "😓",
    shortcode: ":sweat:",
    name: "Downcast Face with Sweat",
    keywords: ["sad", "sweat"],
  },
  {
    unicode: "😩",
    shortcode: ":weary:",
    name: "Weary Face",
    keywords: ["tired", "exhausted"],
  },
  {
    unicode: "😫",
    shortcode: ":tired_face:",
    name: "Tired Face",
    keywords: ["frustrated", "tired"],
  },
  {
    unicode: "🥱",
    shortcode: ":yawning_face:",
    name: "Yawning Face",
    keywords: ["tired", "sleepy"],
  },
  {
    unicode: "😤",
    shortcode: ":triumph:",
    name: "Face with Steam from Nose",
    keywords: ["angry", "frustrated"],
  },
  {
    unicode: "😡",
    shortcode: ":angry:",
    name: "Pouting Face",
    keywords: ["angry", "upset"],
  },
  {
    unicode: "😠",
    shortcode: ":rage:",
    name: "Angry Face",
    keywords: ["angry", "mean"],
  },
  {
    unicode: "🤬",
    shortcode: ":no_mouth:",
    name: "Cursing",
    keywords: ["swear", "angry"],
  },
  {
    unicode: "😈",
    shortcode: ":smiling_imp:",
    name: "Smiling Imp",
    keywords: ["devil", "evil"],
  },
  {
    unicode: "👿",
    shortcode: ":imp:",
    name: "Imp",
    keywords: ["devil", "evil"],
  },
  {
    unicode: "💀",
    shortcode: ":skull:",
    name: "Skull",
    keywords: ["death", "scary"],
  },
  {
    unicode: "☠️",
    shortcode: ":skull_and_crossbones:",
    name: "Skull and Crossbones",
    keywords: ["poison", "danger"],
  },
  {
    unicode: "💩",
    shortcode: ":poop:",
    name: "Pile of Poop",
    keywords: ["poop", "funny"],
  },
  {
    unicode: "🤡",
    shortcode: ":clown_face:",
    name: "Clown Face",
    keywords: ["clown", "joke"],
  },
  {
    unicode: "👹",
    shortcode: ":japanese_ogre:",
    name: "Ogre",
    keywords: ["demon", "scary"],
  },
  {
    unicode: "👺",
    shortcode: ":japanese_goblin:",
    name: "Goblin",
    keywords: ["demon", "scary"],
  },
  {
    unicode: "👻",
    shortcode: ":ghost:",
    name: "Ghost",
    keywords: ["scary", "halloween"],
  },
  {
    unicode: "👽",
    shortcode: ":alien:",
    name: "Alien",
    keywords: ["space", "ufo"],
  },
  {
    unicode: "👾",
    shortcode: ":space_invader:",
    name: "Alien Monster",
    keywords: ["space", "game"],
  },
  {
    unicode: "🤖",
    shortcode: ":robot:",
    name: "Robot",
    keywords: ["machine", "tech"],
  },
  {
    unicode: "😺",
    shortcode: ":smiley_cat:",
    name: "Grinning Cat",
    keywords: ["cat", "happy"],
  },
  {
    unicode: "😸",
    shortcode: ":smile_cat:",
    name: "Smiling Cat",
    keywords: ["cat", "happy"],
  },
  {
    unicode: "😹",
    shortcode: ":joy_cat:",
    name: "Cat with Tears of Joy",
    keywords: ["cat", "laugh"],
  },
  {
    unicode: "😻",
    shortcode: ":heart_eyes_cat:",
    name: "Smiling Cat with Heart Eyes",
    keywords: ["cat", "love"],
  },
  {
    unicode: "😼",
    shortcode: ":smirk_cat:",
    name: "Cat with Wry Smile",
    keywords: ["cat", "sarcasm"],
  },
  {
    unicode: "😽",
    shortcode: ":kissing_cat:",
    name: "Kissing Cat",
    keywords: ["cat", "kiss"],
  },
  {
    unicode: "🙀",
    shortcode: ":weary_cat:",
    name: "Weary Cat",
    keywords: ["cat", "tired"],
  },
  {
    unicode: "😿",
    shortcode: ":crying_cat_face:",
    name: "Crying Cat",
    keywords: ["cat", "sad"],
  },
  {
    unicode: "😾",
    shortcode: ":pouting_cat:",
    name: "Pouting Cat",
    keywords: ["cat", "angry"],
  },

  // Animals & Nature
  {
    unicode: "🐶",
    shortcode: ":dog:",
    name: "Dog Face",
    keywords: ["animal", "dog", "pet"],
  },
  {
    unicode: "🐱",
    shortcode: ":cat:",
    name: "Cat Face",
    keywords: ["animal", "cat", "pet"],
  },
  {
    unicode: "🐭",
    shortcode: ":mouse_face:",
    name: "Mouse Face",
    keywords: ["animal", "mouse", "mickey"],
  },
  {
    unicode: "🐹",
    shortcode: ":hamster:",
    name: "Hamster",
    keywords: ["animal", "hamster"],
  },
  {
    unicode: "🐰",
    shortcode: ":rabbit_face:",
    name: "Rabbit Face",
    keywords: ["animal", "rabbit", "bunny"],
  },
  {
    unicode: "🦊",
    shortcode: ":fox_face:",
    name: "Fox",
    keywords: ["animal", "fox"],
  },
  {
    unicode: "🐻",
    shortcode: ":bear_face:",
    name: "Bear Face",
    keywords: ["animal", "bear"],
  },
  {
    unicode: "🐼",
    shortcode: ":panda:",
    name: "Panda",
    keywords: ["animal", "panda"],
  },
  {
    unicode: "🐨",
    shortcode: ":koala:",
    name: "Koala",
    keywords: ["animal", "koala"],
  },
  {
    unicode: "🐯",
    shortcode: ":tiger_face:",
    name: "Tiger Face",
    keywords: ["animal", "tiger"],
  },
  {
    unicode: "🦁",
    shortcode: ":lion:",
    name: "Lion",
    keywords: ["animal", "lion", "brave"],
  },
  {
    unicode: "🐮",
    shortcode: ":cow_face:",
    name: "Cow Face",
    keywords: ["animal", "cow"],
  },
  {
    unicode: "🐷",
    shortcode: ":pig_face:",
    name: "Pig Face",
    keywords: ["animal", "pig"],
  },
  {
    unicode: "🐽",
    shortcode: ":pig_nose:",
    name: "Pig Nose",
    keywords: ["animal", "pig"],
  },
  {
    unicode: "🐸",
    shortcode: ":frog:",
    name: "Frog",
    keywords: ["animal", "frog"],
  },
  {
    unicode: "🐵",
    shortcode: ":monkey_face:",
    name: "Monkey Face",
    keywords: ["animal", "monkey"],
  },
  {
    unicode: "🙈",
    shortcode: ":see_no_evil:",
    name: "See No Evil Monkey",
    keywords: ["monkey", "blind"],
  },
  {
    unicode: "🙉",
    shortcode: ":hear_no_evil:",
    name: "Hear No Evil Monkey",
    keywords: ["monkey", "deaf"],
  },
  {
    unicode: "🙊",
    shortcode: ":speak_no_evil:",
    name: "Speak No Evil Monkey",
    keywords: ["monkey", "mute"],
  },
  {
    unicode: "🐒",
    shortcode: ":monkey:",
    name: "Monkey",
    keywords: ["animal", "monkey"],
  },
  {
    unicode: "🐔",
    shortcode: ":chicken:",
    name: "Chicken",
    keywords: ["animal", "chicken"],
  },
  {
    unicode: "🐧",
    shortcode: ":penguin:",
    name: "Penguin",
    keywords: ["animal", "penguin", "bird"],
  },
  {
    unicode: "🐦",
    shortcode: ":bird:",
    name: "Bird",
    keywords: ["animal", "bird"],
  },
  {
    unicode: "🐤",
    shortcode: ":baby_chick:",
    name: "Baby Chick",
    keywords: ["animal", "chick", "cute"],
  },
  {
    unicode: "🐣",
    shortcode: ":hatching_chick:",
    name: "Hatching Chick",
    keywords: ["animal", "chick", "egg"],
  },
  {
    unicode: "🐥",
    shortcode: ":front_facing_baby_chick:",
    name: "Front Facing Baby Chick",
    keywords: ["animal", "chick", "cute"],
  },
  {
    unicode: "🦆",
    shortcode: ":duck:",
    name: "Duck",
    keywords: ["animal", "duck"],
  },
  {
    unicode: "🦅",
    shortcode: ":eagle:",
    name: "Eagle",
    keywords: ["animal", "eagle", "bird"],
  },
  {
    unicode: "🦉",
    shortcode: ":owl:",
    name: "Owl",
    keywords: ["animal", "owl", "wise"],
  },
  {
    unicode: "🦇",
    shortcode: ":bat:",
    name: "Bat",
    keywords: ["animal", "bat", "night"],
  },
  {
    unicode: "🐺",
    shortcode: ":wolf:",
    name: "Wolf",
    keywords: ["animal", "wolf", "wild"],
  },
  {
    unicode: "🐗",
    shortcode: ":boar:",
    name: "Boar",
    keywords: ["animal", "boar"],
  },
  {
    unicode: "🐴",
    shortcode: ":horse_face:",
    name: "Horse Face",
    keywords: ["animal", "horse"],
  },
  {
    unicode: "🦄",
    shortcode: ":unicorn:",
    name: "Unicorn",
    keywords: ["fantasy", "magic", "mythical"],
  },
  {
    unicode: "🐝",
    shortcode: ":honeybee:",
    name: "Honeybee",
    keywords: ["animal", "bee", "insect"],
  },
  {
    unicode: "🐛",
    shortcode: ":bug:",
    name: "Bug",
    keywords: ["animal", "insect"],
  },
  {
    unicode: "🦋",
    shortcode: ":butterfly:",
    name: "Butterfly",
    keywords: ["animal", "insect", "butterfly"],
  },
  {
    unicode: "🐌",
    shortcode: ":snail:",
    name: "Snail",
    keywords: ["animal", "snail", "slow"],
  },
  {
    unicode: "🐞",
    shortcode: ":ladybug:",
    name: "Lady Beetle",
    keywords: ["animal", "insect", "ladybug"],
  },
  {
    unicode: "🐜",
    shortcode: ":ant:",
    name: "Ant",
    keywords: ["animal", "insect", "ant"],
  },
  {
    unicode: "🐢",
    shortcode: ":turtle:",
    name: "Turtle",
    keywords: ["animal", "turtle", "slow"],
  },
  {
    unicode: "🐍",
    shortcode: ":snake:",
    name: "Snake",
    keywords: ["animal", "snake", "dangerous"],
  },
  {
    unicode: "🐎",
    shortcode: ":horse:",
    name: "Horse",
    keywords: ["animal", "horse"],
  },
  {
    unicode: "🐙",
    shortcode: ":octopus:",
    name: "Octopus",
    keywords: ["sea", "animal", "octopus"],
  },
  {
    unicode: "🐚",
    shortcode: ":shell:",
    name: "Shell",
    keywords: ["sea", "beach"],
  },
  {
    unicode: "🐠",
    shortcode: ":fish:",
    name: "Fish",
    keywords: ["sea", "animal", "fish"],
  },
  {
    unicode: "🐟",
    shortcode: ":fish:",
    name: "Fish",
    keywords: ["sea", "animal"],
  },
  {
    unicode: "🐬",
    shortcode: ":dolphin:",
    name: "Dolphin",
    keywords: ["sea", "animal", "dolphin"],
  },
  {
    unicode: "🐳",
    shortcode: ":whale:",
    name: "Whale",
    keywords: ["sea", "animal", "whale", "big"],
  },
  {
    unicode: "🐋",
    shortcode: ":whale2:",
    name: "Whale",
    keywords: ["sea", "animal", "whale"],
  },
  {
    unicode: "🦈",
    shortcode: ":shark:",
    name: "Shark",
    keywords: ["sea", "animal", "shark", "danger"],
  },
  {
    unicode: "🐊",
    shortcode: ":crocodile:",
    name: "Crocodile",
    keywords: ["animal", "crocodile", "danger"],
  },
  {
    unicode: "🐅",
    shortcode: ":tiger:",
    name: "Tiger",
    keywords: ["animal", "tiger"],
  },
  {
    unicode: "🐆",
    shortcode: ":leopard:",
    name: "Leopard",
    keywords: ["animal", "leopard"],
  },
  {
    unicode: "🦓",
    shortcode: ":zebra:",
    name: "Zebra",
    keywords: ["animal", "zebra"],
  },
  {
    unicode: "🦍",
    shortcode: ":gorilla:",
    name: "Gorilla",
    keywords: ["animal", "gorilla", "strong"],
  },
  {
    unicode: "🦧",
    shortcode: ":orangutan:",
    name: "Orangutan",
    keywords: ["animal", "orangutan"],
  },
  {
    unicode: "🐘",
    shortcode: ":elephant:",
    name: "Elephant",
    keywords: ["animal", "elephant", "big"],
  },
  {
    unicode: "🦛",
    shortcode: ":hippopotamus:",
    name: "Hippopotamus",
    keywords: ["animal", "hippo"],
  },
  {
    unicode: "🦏",
    shortcode: ":rhinoceros:",
    name: "Rhinoceros",
    keywords: ["animal", "rhino"],
  },
  {
    unicode: "🐪",
    shortcode: ":camel:",
    name: "Camel",
    keywords: ["animal", "camel", "desert"],
  },
  {
    unicode: "🐫",
    shortcode: ":camel2:",
    name: "Camel",
    keywords: ["animal", "camel"],
  },
  {
    unicode: "🦒",
    shortcode: ":giraffe:",
    name: "Giraffe",
    keywords: ["animal", "giraffe", "tall"],
  },
  {
    unicode: "🦘",
    shortcode: ":kangaroo:",
    name: "Kangaroo",
    keywords: ["animal", "kangaroo"],
  },
  {
    unicode: "🐃",
    shortcode: ":water_buffalo:",
    name: "Water Buffalo",
    keywords: ["animal", "buffalo"],
  },
  { unicode: "🐂", shortcode: ":ox:", name: "Ox", keywords: ["animal", "ox"] },
  {
    unicode: "🐄",
    shortcode: ":cow:",
    name: "Cow",
    keywords: ["animal", "cow"],
  },
  {
    unicode: "🐎",
    shortcode: ":horse:",
    name: "Horse",
    keywords: ["animal", "horse"],
  },
  {
    unicode: "🐖",
    shortcode: ":pig:",
    name: "Pig",
    keywords: ["animal", "pig"],
  },
  {
    unicode: "🐏",
    shortcode: ":ram:",
    name: "Ram",
    keywords: ["animal", "sheep"],
  },
  {
    unicode: "🐑",
    shortcode: ":sheep:",
    name: "Sheep",
    keywords: ["animal", "sheep"],
  },
  {
    unicode: "🦌",
    shortcode: ":deer:",
    name: "Deer",
    keywords: ["animal", "deer"],
  },
  {
    unicode: "🐐",
    shortcode: ":goat:",
    name: "Goat",
    keywords: ["animal", "goat"],
  },
  {
    unicode: "🦌",
    shortcode: ":deer:",
    name: "Deer",
    keywords: ["animal", "deer", "nature"],
  },
  {
    unicode: "🐕",
    shortcode: ":dog:",
    name: "Dog",
    keywords: ["animal", "dog", "pet"],
  },
  {
    unicode: "🐩",
    shortcode: ":poodle:",
    name: "Poodle",
    keywords: ["animal", "dog", "poodle"],
  },
  {
    unicode: "🦮",
    shortcode: ":guide_dog:",
    name: "Guide Dog",
    keywords: ["dog", "help", "assist"],
  },
  {
    unicode: "🐈",
    shortcode: ":cat:",
    name: "Cat",
    keywords: ["animal", "cat", "pet"],
  },
  {
    unicode: "🐓",
    shortcode: ":rooster:",
    name: "Rooster",
    keywords: ["animal", "rooster", "chicken"],
  },
  {
    unicode: "🦃",
    shortcode: ":turkey:",
    name: "Turkey",
    keywords: ["animal", "turkey", "thanksgiving"],
  },
  {
    unicode: "🦚",
    shortcode: ":peacock:",
    name: "Peacock",
    keywords: ["animal", "bird", "peacock"],
  },
  {
    unicode: "🦜",
    shortcode: ":parrot:",
    name: "Parrot",
    keywords: ["animal", "bird", "parrot"],
  },
  {
    unicode: "🦢",
    shortcode: ":swan:",
    name: "Swan",
    keywords: ["animal", "bird", "swan", "elegant"],
  },
  {
    unicode: "🦗",
    shortcode: ":cricket:",
    name: "Cricket",
    keywords: ["animal", "insect", "cricket"],
  },
  { unicode: "🥚", shortcode: ":egg:", name: "Egg", keywords: ["food", "egg"] },

  // Food & Drink
  {
    unicode: "🍏",
    shortcode: ":green_apple:",
    name: "Green Apple",
    keywords: ["fruit", "food", "apple"],
  },
  {
    unicode: "🍎",
    shortcode: ":apple:",
    name: "Red Apple",
    keywords: ["fruit", "food", "apple"],
  },
  {
    unicode: "🍐",
    shortcode: ":pear:",
    name: "Pear",
    keywords: ["fruit", "food"],
  },
  {
    unicode: "🍊",
    shortcode: ":orange:",
    name: "Orange",
    keywords: ["fruit", "food", "orange"],
  },
  {
    unicode: "🍋",
    shortcode: ":lemon:",
    name: "Lemon",
    keywords: ["fruit", "food", "lemon", "sour"],
  },
  {
    unicode: "🍌",
    shortcode: ":banana:",
    name: "Banana",
    keywords: ["fruit", "food", "banana", "yellow"],
  },
  {
    unicode: "🍉",
    shortcode: ":watermelon:",
    name: "Watermelon",
    keywords: ["fruit", "food", "watermelon", "summer"],
  },
  {
    unicode: "🍇",
    shortcode: ":grapes:",
    name: "Grapes",
    keywords: ["fruit", "food", "grapes"],
  },
  {
    unicode: "🍓",
    shortcode: ":strawberry:",
    name: "Strawberry",
    keywords: ["fruit", "food", "strawberry", "red"],
  },
  {
    unicode: "🍈",
    shortcode: ":melon:",
    name: "Melon",
    keywords: ["fruit", "food", "melon"],
  },
  {
    unicode: "🍒",
    shortcode: ":cherries:",
    name: "Cherries",
    keywords: ["fruit", "food", "cherries"],
  },
  {
    unicode: "🍑",
    shortcode: ":peach:",
    name: "Peach",
    keywords: ["fruit", "food", "peach"],
  },
  {
    unicode: "🥭",
    shortcode: ":mango:",
    name: "Mango",
    keywords: ["fruit", "food", "mango", "tropical"],
  },
  {
    unicode: "🍍",
    shortcode: ":pineapple:",
    name: "Pineapple",
    keywords: ["fruit", "food", "pineapple", "tropical"],
  },
  {
    unicode: "🥥",
    shortcode: ":coconut:",
    name: "Coconut",
    keywords: ["fruit", "food", "coconut", "tropical"],
  },
  {
    unicode: "🥝",
    shortcode: ":kiwi_fruit:",
    name: "Kiwi Fruit",
    keywords: ["fruit", "food", "kiwi", "green"],
  },
  {
    unicode: "🍅",
    shortcode: ":tomato:",
    name: "Tomato",
    keywords: ["vegetable", "food", "tomato", "red"],
  },
  {
    unicode: "🍆",
    shortcode: ":eggplant:",
    name: "Eggplant",
    keywords: ["vegetable", "food", "eggplant", "purple"],
  },
  {
    unicode: "🥑",
    shortcode: ":avocado:",
    name: "Avocado",
    keywords: ["vegetable", "food", "avocado", "green"],
  },
  {
    unicode: "🥦",
    shortcode: ":broccoli:",
    name: "Broccoli",
    keywords: ["vegetable", "food", "broccoli", "green"],
  },
  {
    unicode: "🥬",
    shortcode: ":leafy_green:",
    name: "Leafy Green",
    keywords: ["vegetable", "food", "green"],
  },
  {
    unicode: "🥒",
    shortcode: ":cucumber:",
    name: "Cucumber",
    keywords: ["vegetable", "food", "cucumber", "green"],
  },
  {
    unicode: "🌶️",
    shortcode: ":hot_pepper:",
    name: "Hot Pepper",
    keywords: ["vegetable", "food", "pepper", "spicy", "red"],
  },
  {
    unicode: "🌽",
    shortcode: ":corn:",
    name: "Corn",
    keywords: ["vegetable", "food", "corn", "yellow"],
  },
  {
    unicode: "🥕",
    shortcode: ":carrot:",
    name: "Carrot",
    keywords: ["vegetable", "food", "carrot", "orange"],
  },
  {
    unicode: "🧄",
    shortcode: ":garlic:",
    name: "Garlic",
    keywords: ["vegetable", "food", "garlic"],
  },
  {
    unicode: "🧅",
    shortcode: ":onion:",
    name: "Onion",
    keywords: ["vegetable", "food", "onion"],
  },
  {
    unicode: "🥔",
    shortcode: ":potato:",
    name: "Potato",
    keywords: ["vegetable", "food", "potato"],
  },
  {
    unicode: "🍠",
    shortcode: ":sweet_potato:",
    name: "Sweet Potato",
    keywords: ["vegetable", "food", "potato"],
  },
  {
    unicode: "🥐",
    shortcode: ":croissant:",
    name: "Croissant",
    keywords: ["bread", "food", "breakfast", "french"],
  },
  {
    unicode: "🥯",
    shortcode: ":bagel:",
    name: "Bagel",
    keywords: ["bread", "food", "bagel"],
  },
  {
    unicode: "🍞",
    shortcode: ":bread:",
    name: "Bread",
    keywords: ["bread", "food", "grain"],
  },
  {
    unicode: "🥖",
    shortcode: ":baguette_bread:",
    name: "Baguette Bread",
    keywords: ["bread", "food", "french"],
  },
  {
    unicode: "🥨",
    shortcode: ":pretzel:",
    name: "Pretzel",
    keywords: ["bread", "food", "pretzel", "snack"],
  },
  {
    unicode: "🧀",
    shortcode: ":cheese:",
    name: "Cheese",
    keywords: ["food", "cheese", "dairy"],
  },
  {
    unicode: "🥚",
    shortcode: ":egg:",
    name: "Egg",
    keywords: ["food", "egg", "breakfast"],
  },
  {
    unicode: "🍳",
    shortcode: ":cooking:",
    name: "Cooking",
    keywords: ["food", "fried", "egg"],
  },
  {
    unicode: "🧈",
    shortcode: ":butter:",
    name: "Butter",
    keywords: ["food", "butter", "dairy"],
  },
  {
    unicode: "🥞",
    shortcode: ":pancakes:",
    name: "Pancakes",
    keywords: ["food", "pancakes", "breakfast"],
  },
  {
    unicode: "🥓",
    shortcode: ":bacon:",
    name: "Bacon",
    keywords: ["food", "bacon", "meat", "breakfast"],
  },
  {
    unicode: "🍗",
    shortcode: ":poultry_leg:",
    name: "Poultry Leg",
    keywords: ["food", "meat", "chicken"],
  },
  {
    unicode: "🍖",
    shortcode: ":meat_on_bone:",
    name: "Meat on Bone",
    keywords: ["food", "meat"],
  },
  {
    unicode: "🌭",
    shortcode: ":hotdog:",
    name: "Hot Dog",
    keywords: ["food", "hotdog", "sausage"],
  },
  {
    unicode: "🍔",
    shortcode: ":hamburger:",
    name: "Hamburger",
    keywords: ["food", "hamburger", "burger", "meat"],
  },
  {
    unicode: "🍟",
    shortcode: ":fries:",
    name: "French Fries",
    keywords: ["food", "fries", "fast food"],
  },
  {
    unicode: "🍕",
    shortcode: ":pizza:",
    name: "Pizza",
    keywords: ["food", "pizza", "italian", "cheese"],
  },
  {
    unicode: "🥪",
    shortcode: ":sandwich:",
    name: "Sandwich",
    keywords: ["food", "sandwich", "bread"],
  },
  {
    unicode: "🥙",
    shortcode: ":stuffed_flatbread:",
    name: "Stuffed Flatbread",
    keywords: ["food", "sandwich"],
  },
  {
    unicode: "🧆",
    shortcode: ":falafel:",
    name: "Falafel",
    keywords: ["food", "falafel", "vegetarian"],
  },
  {
    unicode: "🌮",
    shortcode: ":taco:",
    name: "Taco",
    keywords: ["food", "taco", "mexican"],
  },
  {
    unicode: "🌯",
    shortcode: ":burrito:",
    name: "Burrito",
    keywords: ["food", "burrito", "mexican"],
  },
  {
    unicode: "🥗",
    shortcode: ":green_salad:",
    name: "Green Salad",
    keywords: ["food", "salad", "vegetarian", "healthy"],
  },
  {
    unicode: "🥘",
    shortcode: ":shallow_pan_of_food:",
    name: "Shallow Pan of Food",
    keywords: ["food", "cooking"],
  },
  {
    unicode: "🥫",
    shortcode: ":canned_food:",
    name: "Canned Food",
    keywords: ["food", "can"],
  },
  {
    unicode: "🍝",
    shortcode: ":spaghetti:",
    name: "Spaghetti",
    keywords: ["food", "pasta", "italian"],
  },
  {
    unicode: "🍜",
    shortcode: ":ramen:",
    name: "Ramen",
    keywords: ["food", "noodles", "ramen", "asian"],
  },
  {
    unicode: "🍲",
    shortcode: ":popcorn:",
    name: "Soup",
    keywords: ["food", "soup", "hot"],
  },
  {
    unicode: "🍛",
    shortcode: ":curry_rice:",
    name: "Curry Rice",
    keywords: ["food", "curry", "asian", "spicy"],
  },
  {
    unicode: "🍣",
    shortcode: ":sushi:",
    name: "Sushi",
    keywords: ["food", "sushi", "japanese", "seafood"],
  },
  {
    unicode: "🍱",
    shortcode: ":bento:",
    name: "Bento Box",
    keywords: ["food", "bento", "japanese"],
  },
  {
    unicode: "🥟",
    shortcode: ":dumpling:",
    name: "Dumpling",
    keywords: ["food", "dumpling", "asian"],
  },
  {
    unicode: "🦪",
    shortcode: ":oyster:",
    name: "Oyster",
    keywords: ["food", "oyster", "seafood"],
  },
  {
    unicode: "🍤",
    shortcode: ":fried_shrimp:",
    name: "Fried Shrimp",
    keywords: ["food", "shrimp", "seafood"],
  },
  {
    unicode: "🍙",
    shortcode: ":rice_ball:",
    name: "Rice Ball",
    keywords: ["food", "rice", "japanese"],
  },
  {
    unicode: "🍚",
    shortcode: ":rice:",
    name: "Cooked Rice",
    keywords: ["food", "rice", "grain"],
  },
  {
    unicode: "🍘",
    shortcode: ":rice_cracker:",
    name: "Rice Cracker",
    keywords: ["food", "rice", "snack"],
  },
  {
    unicode: "🍥",
    shortcode: ":fish_cake_with_swirl:",
    name: "Fish Cake with Swirl",
    keywords: ["food", "cake", "fish"],
  },
  {
    unicode: "🥠",
    shortcode: ":fortune_cookie:",
    name: "Fortune Cookie",
    keywords: ["food", "cookie", "dessert", "lucky"],
  },
  {
    unicode: "🥮",
    shortcode: ":moon_cake:",
    name: "Moon Cake",
    keywords: ["food", "cake", "asian"],
  },
  {
    unicode: "🍢",
    shortcode: ":oden:",
    name: "Oden",
    keywords: ["food", "asian", "skewer"],
  },
  {
    unicode: "🍡",
    shortcode: ":dango:",
    name: "Dango",
    keywords: ["food", "dumpling", "japanese", "sweet"],
  },
  {
    unicode: "🍧",
    shortcode: ":shaved_ice:",
    name: "Shaved Ice",
    keywords: ["food", "ice", "dessert", "cold"],
  },
  {
    unicode: "🍨",
    shortcode: ":ice_cream:",
    name: "Ice Cream",
    keywords: ["food", "ice cream", "dessert", "cold", "sweet"],
  },
  {
    unicode: "🍦",
    shortcode: ":soft_ice_cream:",
    name: "Soft Ice Cream",
    keywords: ["food", "ice cream", "dessert", "sweet"],
  },
  {
    unicode: "🍰",
    shortcode: ":cake:",
    name: "Cake",
    keywords: ["food", "cake", "dessert", "sweet", "birthday"],
  },
  {
    unicode: "🎂",
    shortcode: ":birthday_cake:",
    name: "Birthday Cake",
    keywords: ["food", "cake", "birthday", "celebration", "dessert"],
  },
  {
    unicode: "🧁",
    shortcode: ":cupcake:",
    name: "Cupcake",
    keywords: ["food", "cupcake", "dessert", "sweet"],
  },
  {
    unicode: "🍮",
    shortcode: ":custard:",
    name: "Custard",
    keywords: ["food", "custard", "dessert", "sweet"],
  },
  {
    unicode: "🍭",
    shortcode: ":lollipop:",
    name: "Lollipop",
    keywords: ["food", "lollipop", "candy", "sweet"],
  },
  {
    unicode: "🍬",
    shortcode: ":candy:",
    name: "Candy",
    keywords: ["food", "candy", "sweet"],
  },
  {
    unicode: "🍫",
    shortcode: ":chocolate_bar:",
    name: "Chocolate Bar",
    keywords: ["food", "chocolate", "sweet", "dessert"],
  },
  {
    unicode: "🍿",
    shortcode: ":popcorn:",
    name: "Popcorn",
    keywords: ["food", "popcorn", "snack", "movie"],
  },
  {
    unicode: "🍩",
    shortcode: ":doughnut:",
    name: "Doughnut",
    keywords: ["food", "donut", "doughnut", "sweet", "dessert"],
  },
  {
    unicode: "🍪",
    shortcode: ":cookie:",
    name: "Cookie",
    keywords: ["food", "cookie", "sweet", "dessert"],
  },
  {
    unicode: "🌰",
    shortcode: ":chestnut:",
    name: "Chestnut",
    keywords: ["food", "nut", "food"],
  },
  {
    unicode: "🍯",
    shortcode: ":honey_pot:",
    name: "Honey Pot",
    keywords: ["food", "honey", "sweet"],
  },
  {
    unicode: "🥛",
    shortcode: ":glass_of_milk:",
    name: "Glass of Milk",
    keywords: ["food", "milk", "drink", "dairy", "white"],
  },
  {
    unicode: "🍼",
    shortcode: ":baby_bottle:",
    name: "Baby Bottle",
    keywords: ["food", "bottle", "drink", "baby"],
  },
  {
    unicode: "☕",
    shortcode: ":coffee:",
    name: "Coffee",
    keywords: ["drink", "coffee", "hot", "morning", "brown"],
  },
  {
    unicode: "🍵",
    shortcode: ":tea:",
    name: "Tea",
    keywords: ["drink", "tea", "hot", "beverage"],
  },
  {
    unicode: "🍶",
    shortcode: ":sake:",
    name: "Sake",
    keywords: ["drink", "sake", "alcohol", "japanese"],
  },
  {
    unicode: "🍾",
    shortcode: ":bottle_with_popping_cork:",
    name: "Bottle with Popping Cork",
    keywords: ["drink", "alcohol", "champagne", "celebration"],
  },
  {
    unicode: "🍷",
    shortcode: ":wine_glass:",
    name: "Wine Glass",
    keywords: ["drink", "wine", "alcohol", "red"],
  },
  {
    unicode: "🍸",
    shortcode: ":cocktail_glass:",
    name: "Cocktail Glass",
    keywords: ["drink", "cocktail", "alcohol"],
  },
  {
    unicode: "🍹",
    shortcode: ":tropical_drink:",
    name: "Tropical Drink",
    keywords: ["drink", "tropical", "vacation", "colorful"],
  },
  {
    unicode: "🍺",
    shortcode: ":beer_mug:",
    name: "Beer Mug",
    keywords: ["drink", "beer", "alcohol", "golden"],
  },
  {
    unicode: "🍻",
    shortcode: ":clinking_beer_mugs:",
    name: "Clinking Beer Mugs",
    keywords: ["drink", "beer", "toast", "celebration"],
  },
  {
    unicode: "🥂",
    shortcode: ":clinking_glasses:",
    name: "Clinking Glasses",
    keywords: ["drink", "champagne", "celebration", "toast"],
  },
  {
    unicode: "🥃",
    shortcode: ":tumbler_glass:",
    name: "Tumbler Glass",
    keywords: ["drink", "glass"],
  },
  {
    unicode: "🥤",
    shortcode: ":cup_with_straw:",
    name: "Cup with Straw",
    keywords: ["drink", "beverage"],
  },

  // Activities & Sports
  {
    unicode: "⚽",
    shortcode: ":soccer:",
    name: "Soccer Ball",
    keywords: ["sports", "soccer", "football", "ball"],
  },
  {
    unicode: "🏀",
    shortcode: ":basketball:",
    name: "Basketball",
    keywords: ["sports", "basketball", "ball"],
  },
  {
    unicode: "🏈",
    shortcode: ":american_football:",
    name: "American Football",
    keywords: ["sports", "football", "ball"],
  },
  {
    unicode: "⚾",
    shortcode: ":baseball:",
    name: "Baseball",
    keywords: ["sports", "baseball", "ball"],
  },
  {
    unicode: "🥎",
    shortcode: ":softball:",
    name: "Softball",
    keywords: ["sports", "softball", "ball"],
  },
  {
    unicode: "🎾",
    shortcode: ":tennis:",
    name: "Tennis",
    keywords: ["sports", "tennis", "ball"],
  },
  {
    unicode: "🏐",
    shortcode: ":volleyball:",
    name: "Volleyball",
    keywords: ["sports", "volleyball", "ball"],
  },
  {
    unicode: "🏉",
    shortcode: ":rugby_football:",
    name: "Rugby Football",
    keywords: ["sports", "rugby", "ball"],
  },
  {
    unicode: "🥏",
    shortcode: ":cricket_game:",
    name: "Cricket Game",
    keywords: ["sports", "cricket", "bat"],
  },
  {
    unicode: "🎳",
    shortcode: ":bowling:",
    name: "Bowling",
    keywords: ["sports", "bowling", "pins"],
  },
  {
    unicode: "🏓",
    shortcode: ":ping_pong:",
    name: "Ping Pong",
    keywords: ["sports", "ping pong", "table tennis"],
  },
  {
    unicode: "🏸",
    shortcode: ":badminton:",
    name: "Badminton",
    keywords: ["sports", "badminton", "racket"],
  },
  {
    unicode: "🏒",
    shortcode: ":ice_hockey:",
    name: "Ice Hockey",
    keywords: ["sports", "hockey", "ice"],
  },
  {
    unicode: "🏑",
    shortcode: ":field_hockey:",
    name: "Field Hockey",
    keywords: ["sports", "hockey", "field"],
  },
  {
    unicode: "🥍",
    shortcode: ":lacrosse:",
    name: "Lacrosse",
    keywords: ["sports", "lacrosse", "stick"],
  },
  {
    unicode: "🏏",
    shortcode: ":cricket_bat_and_ball:",
    name: "Cricket Bat and Ball",
    keywords: ["sports", "cricket"],
  },
  {
    unicode: "⛳",
    shortcode: ":golf:",
    name: "Golf",
    keywords: ["sports", "golf", "flag", "hole"],
  },
  {
    unicode: "⛸️",
    shortcode: ":ice_skate:",
    name: "Ice Skate",
    keywords: ["sports", "ice skating", "winter"],
  },
  {
    unicode: "🎣",
    shortcode: ":fishing_pole_and_fish:",
    name: "Fishing Pole and Fish",
    keywords: ["sports", "fishing", "hobby"],
  },
  {
    unicode: "🎽",
    shortcode: ":running_shirt_with_sash:",
    name: "Running Shirt",
    keywords: ["sports", "running", "shirt"],
  },
  {
    unicode: "🎿",
    shortcode: ":skis:",
    name: "Skis",
    keywords: ["sports", "skiing", "winter", "snow"],
  },
  {
    unicode: "⛷️",
    shortcode: ":skier:",
    name: "Skier",
    keywords: ["sports", "skiing", "winter"],
  },
  {
    unicode: "🏂",
    shortcode: ":snowboarder:",
    name: "Snowboarder",
    keywords: ["sports", "snowboarding", "winter", "snow"],
  },
  {
    unicode: "🪂",
    shortcode: ":parachute:",
    name: "Parachute",
    keywords: ["sports", "parachute", "extreme", "sky"],
  },
  {
    unicode: "🛼",
    shortcode: ":roller_skate:",
    name: "Roller Skate",
    keywords: ["sports", "roller skate", "retro"],
  },
  {
    unicode: "🛹",
    shortcode: ":skateboard:",
    name: "Skateboard",
    keywords: ["sports", "skateboard", "extreme"],
  },
  {
    unicode: "🛺",
    shortcode: ":auto_rickshaw:",
    name: "Auto Rickshaw",
    keywords: ["transport", "rickshaw"],
  },
  {
    unicode: "🏋️",
    shortcode: ":weight_lifter:",
    name: "Weight Lifter",
    keywords: ["sports", "weightlifting", "gym", "strong"],
  },
  {
    unicode: "🏊",
    shortcode: ":swimmer:",
    name: "Swimmer",
    keywords: ["sports", "swimming", "water"],
  },
  {
    unicode: "🤽",
    shortcode: ":water_polo:",
    name: "Water Polo",
    keywords: ["sports", "water polo", "water"],
  },
  {
    unicode: "🚣",
    shortcode: ":rowing_person:",
    name: "Rowing Person",
    keywords: ["sports", "rowing", "boat", "water"],
  },
  {
    unicode: "🧗",
    shortcode: ":climbing_person:",
    name: "Climbing Person",
    keywords: ["sports", "climbing", "rock", "extreme"],
  },
  {
    unicode: "🚴",
    shortcode: ":person_biking:",
    name: "Person Biking",
    keywords: ["sports", "biking", "cycling"],
  },
  {
    unicode: "🚵",
    shortcode: ":person_mountain_biking:",
    name: "Person Mountain Biking",
    keywords: ["sports", "mountain biking", "extreme"],
  },
  {
    unicode: "🎯",
    shortcode: ":direct_hit:",
    name: "Direct Hit",
    keywords: ["sports", "target", "goal", "aim"],
  },
  {
    unicode: "🪀",
    shortcode: ":yo_yo:",
    name: "Yo-yo",
    keywords: ["toy", "yo-yo", "retro"],
  },
  {
    unicode: "🪃",
    shortcode: ":boomerang:",
    name: "Boomerang",
    keywords: ["toy", "boomerang"],
  },
  {
    unicode: "🎮",
    shortcode: ":video_game:",
    name: "Video Game",
    keywords: ["gaming", "game", "console", "entertainment"],
  },
  {
    unicode: "🎲",
    shortcode: ":game_die:",
    name: "Game Die",
    keywords: ["gaming", "dice", "chance"],
  },
  {
    unicode: "♟️",
    shortcode: ":chess_pawn:",
    name: "Chess Pawn",
    keywords: ["gaming", "chess", "board game"],
  },
  {
    unicode: "🎭",
    shortcode: ":performing_arts:",
    name: "Performing Arts",
    keywords: ["entertainment", "theater", "drama", "masks"],
  },
  {
    unicode: "🎨",
    shortcode: ":art:",
    name: "Artist Palette",
    keywords: ["art", "creative", "painting", "colorful"],
  },
  {
    unicode: "🎬",
    shortcode: ":clapper_board:",
    name: "Clapper Board",
    keywords: ["entertainment", "movie", "film", "cinema"],
  },
  {
    unicode: "🎤",
    shortcode: ":microphone:",
    name: "Microphone",
    keywords: ["entertainment", "singing", "music", "audio"],
  },
  {
    unicode: "🎧",
    shortcode: ":headphones:",
    name: "Headphones",
    keywords: ["audio", "music", "listening", "entertainment"],
  },
  {
    unicode: "🎼",
    shortcode: ":musical_score:",
    name: "Musical Score",
    keywords: ["music", "notes", "song"],
  },
  {
    unicode: "🎹",
    shortcode: ":musical_keyboard:",
    name: "Musical Keyboard",
    keywords: ["music", "piano", "keyboard", "instrument"],
  },
  {
    unicode: "🥁",
    shortcode: ":drum:",
    name: "Drum",
    keywords: ["music", "drum", "instrument", "percussion"],
  },
  {
    unicode: "🎷",
    shortcode: ":saxophone:",
    name: "Saxophone",
    keywords: ["music", "saxophone", "instrument", "jazz"],
  },
  {
    unicode: "🎺",
    shortcode: ":trumpet:",
    name: "Trumpet",
    keywords: ["music", "trumpet", "instrument", "brass"],
  },
  {
    unicode: "🎸",
    shortcode: ":guitar:",
    name: "Guitar",
    keywords: ["music", "guitar", "instrument", "rock"],
  },
  {
    unicode: "🪕",
    shortcode: ":banjo:",
    name: "Banjo",
    keywords: ["music", "banjo", "instrument"],
  },
  {
    unicode: "🎻",
    shortcode: ":violin:",
    name: "Violin",
    keywords: ["music", "violin", "instrument", "classical"],
  },

  // Party & Celebration
  {
    unicode: "🎉",
    shortcode: ":party_popper:",
    name: "Party Popper",
    keywords: ["party", "celebration", "birthday", "confetti", "fun"],
  },
  {
    unicode: "🎊",
    shortcode: ":confetti_ball:",
    name: "Confetti Ball",
    keywords: ["party", "celebration", "birthday", "confetti"],
  },
  {
    unicode: "🎈",
    shortcode: ":balloon:",
    name: "Balloon",
    keywords: ["party", "birthday", "celebration", "colorful"],
  },
  {
    unicode: "🎁",
    shortcode: ":gift:",
    name: "Wrapped Gift",
    keywords: ["party", "gift", "birthday", "present", "celebration"],
  },
  {
    unicode: "🎀",
    shortcode: ":ribbon:",
    name: "Ribbon",
    keywords: ["party", "gift", "bow", "celebration"],
  },
  {
    unicode: "🎂",
    shortcode: ":birthday_cake:",
    name: "Birthday Cake",
    keywords: ["birthday", "cake", "celebration", "party", "dessert"],
  },
  {
    unicode: "🎃",
    shortcode: ":jack_o_lantern:",
    name: "Jack-o'-Lantern",
    keywords: ["halloween", "pumpkin", "scary", "celebration"],
  },
  {
    unicode: "🎄",
    shortcode: ":christmas_tree:",
    name: "Christmas Tree",
    keywords: ["christmas", "holiday", "tree", "winter", "celebration"],
  },
  {
    unicode: "🎆",
    shortcode: ":fireworks:",
    name: "Fireworks",
    keywords: ["celebration", "fireworks", "party", "night"],
  },
  {
    unicode: "🎇",
    shortcode: ":sparkler:",
    name: "Sparkler",
    keywords: ["celebration", "fireworks", "sparkle", "light"],
  },
  {
    unicode: "🥳",
    shortcode: ":partying_face:",
    name: "Partying Face",
    keywords: ["party", "celebration", "birthday", "happy", "fun"],
  },
  {
    unicode: "✨",
    shortcode: ":sparkles:",
    name: "Sparkles",
    keywords: ["celebration", "magic", "sparkle", "shine", "glitter"],
  },

  // Hearts & Love
  {
    unicode: "❤️",
    shortcode: ":red_heart:",
    name: "Red Heart",
    keywords: ["heart", "love", "red", "emotion"],
  },
  {
    unicode: "🧡",
    shortcode: ":orange_heart:",
    name: "Orange Heart",
    keywords: ["heart", "orange", "love"],
  },
  {
    unicode: "💛",
    shortcode: ":yellow_heart:",
    name: "Yellow Heart",
    keywords: ["heart", "yellow", "love", "happy"],
  },
  {
    unicode: "💚",
    shortcode: ":green_heart:",
    name: "Green Heart",
    keywords: ["heart", "green", "love", "nature"],
  },
  {
    unicode: "💙",
    shortcode: ":blue_heart:",
    name: "Blue Heart",
    keywords: ["heart", "blue", "love", "calm"],
  },
  {
    unicode: "💜",
    shortcode: ":purple_heart:",
    name: "Purple Heart",
    keywords: ["heart", "purple", "love", "magic"],
  },
  {
    unicode: "🖤",
    shortcode: ":black_heart:",
    name: "Black Heart",
    keywords: ["heart", "black", "dark"],
  },
  {
    unicode: "🤍",
    shortcode: ":white_heart:",
    name: "White Heart",
    keywords: ["heart", "white", "pure"],
  },
  {
    unicode: "🤎",
    shortcode: ":brown_heart:",
    name: "Brown Heart",
    keywords: ["heart", "brown"],
  },
  {
    unicode: "💔",
    shortcode: ":broken_heart:",
    name: "Broken Heart",
    keywords: ["heart", "broken", "sad"],
  },
  {
    unicode: "💕",
    shortcode: ":two_hearts:",
    name: "Two Hearts",
    keywords: ["heart", "love", "couple"],
  },
  {
    unicode: "💞",
    shortcode: ":revolving_hearts:",
    name: "Revolving Hearts",
    keywords: ["heart", "love", "couple"],
  },
  {
    unicode: "💓",
    shortcode: ":beating_heart:",
    name: "Beating Heart",
    keywords: ["heart", "love", "emotion"],
  },
  {
    unicode: "💗",
    shortcode: ":growing_heart:",
    name: "Growing Heart",
    keywords: ["heart", "love", "emotion"],
  },
  {
    unicode: "💖",
    shortcode: ":sparkling_heart:",
    name: "Sparkling Heart",
    keywords: ["heart", "love", "sparkle"],
  },
  {
    unicode: "💘",
    shortcode: ":cupid:",
    name: "Cupid",
    keywords: ["heart", "love", "arrow", "romance"],
  },
  {
    unicode: "💝",
    shortcode: ":heart_decoration:",
    name: "Heart Decoration",
    keywords: ["heart", "gift", "love"],
  },
  {
    unicode: "💟",
    shortcode: ":heart_exclamation:",
    name: "Heart Exclamation",
    keywords: ["heart", "love"],
  },

  // Symbols & Sparkles
  {
    unicode: "⭐",
    shortcode: ":star:",
    name: "Star",
    keywords: ["star", "sparkle", "night", "magic", "wish"],
  },
  {
    unicode: "🌟",
    shortcode: ":glowing_star:",
    name: "Glowing Star",
    keywords: ["star", "sparkle", "bright", "magic"],
  },
  {
    unicode: "✨",
    shortcode: ":sparkles:",
    name: "Sparkles",
    keywords: ["sparkle", "magic", "shine", "glitter", "celebration"],
  },
  {
    unicode: "⚡",
    shortcode: ":zap:",
    name: "Lightning",
    keywords: ["lightning", "electricity", "fast", "power"],
  },
  {
    unicode: "☄️",
    shortcode: ":comet:",
    name: "Comet",
    keywords: ["comet", "space", "meteor"],
  },
  {
    unicode: "💥",
    shortcode: ":explosion:",
    name: "Explosion",
    keywords: ["explosion", "boom", "energy", "pow"],
  },
  {
    unicode: "🔥",
    shortcode: ":fire:",
    name: "Fire",
    keywords: ["fire", "hot", "flame", "danger", "hot"],
  },
  {
    unicode: "🌈",
    shortcode: ":rainbow:",
    name: "Rainbow",
    keywords: ["rainbow", "colorful", "beautiful", "sky", "hope"],
  },
  {
    unicode: "☀️",
    shortcode: ":sun_with_face:",
    name: "Sun",
    keywords: ["sun", "bright", "day", "weather", "summer"],
  },
  {
    unicode: "🌤️",
    shortcode: ":sun_small_cloud:",
    name: "Sun Behind Small Cloud",
    keywords: ["sun", "cloud", "weather", "sunny"],
  },
  {
    unicode: "⛅",
    shortcode: ":sun_behind_cloud:",
    name: "Sun Behind Cloud",
    keywords: ["sun", "cloud", "weather"],
  },
  {
    unicode: "🌥️",
    shortcode: ":cloud_sun:",
    name: "Cloud",
    keywords: ["cloud", "weather", "sky"],
  },
  {
    unicode: "☁️",
    shortcode: ":cloud:",
    name: "Cloud",
    keywords: ["cloud", "weather", "sky", "fluffy"],
  },
  {
    unicode: "🌦️",
    shortcode: ":rain_cloud:",
    name: "Rain Cloud",
    keywords: ["rain", "cloud", "weather"],
  },
  {
    unicode: "🌧️",
    shortcode: ":cloud_with_rain:",
    name: "Cloud with Rain",
    keywords: ["rain", "cloud", "weather", "wet"],
  },
  {
    unicode: "⛈️",
    shortcode: ":thunderstorm:",
    name: "Thunderstorm",
    keywords: ["storm", "thunder", "lightning", "weather"],
  },
  {
    unicode: "🌩️",
    shortcode: ":lightning_cloud:",
    name: "Lightning Cloud",
    keywords: ["lightning", "cloud", "weather", "storm"],
  },
  {
    unicode: "🌨️",
    shortcode: ":snow_cloud:",
    name: "Snow Cloud",
    keywords: ["snow", "cloud", "weather", "winter", "cold"],
  },
  {
    unicode: "❄️",
    shortcode: ":snowflake:",
    name: "Snowflake",
    keywords: ["snow", "winter", "cold", "ice"],
  },
  {
    unicode: "☃️",
    shortcode: ":snowman:",
    name: "Snowman",
    keywords: ["snowman", "winter", "snow", "cold"],
  },
  {
    unicode: "⛄",
    shortcode: ":snowman_wo_snow:",
    name: "Snowman Without Snow",
    keywords: ["snowman", "winter"],
  },
  {
    unicode: "🌬️",
    shortcode: ":wind_face:",
    name: "Wind Face",
    keywords: ["wind", "weather", "blow"],
  },
  {
    unicode: "💨",
    shortcode: ":dashing_away:",
    name: "Dashing Away",
    keywords: ["wind", "speed", "fast", "motion"],
  },
  {
    unicode: "💧",
    shortcode: ":droplet:",
    name: "Water Droplet",
    keywords: ["water", "drop", "rain", "weather"],
  },
  {
    unicode: "💦",
    shortcode: ":sweat_droplets:",
    name: "Sweat Droplets",
    keywords: ["water", "sweat", "splash"],
  },
  {
    unicode: "☔",
    shortcode: ":umbrella_with_rain_drops:",
    name: "Umbrella with Rain Drops",
    keywords: ["rain", "umbrella", "weather"],
  },
  {
    unicode: "🍀",
    shortcode: ":four_leaf_clover:",
    name: "Four Leaf Clover",
    keywords: ["clover", "luck", "lucky", "green", "nature"],
  },
  {
    unicode: "🎋",
    shortcode: ":tanabata_tree:",
    name: "Tanabata Tree",
    keywords: ["tree", "bamboo", "decoration"],
  },
  {
    unicode: "🎍",
    shortcode: ":pine_decoration:",
    name: "Pine Decoration",
    keywords: ["tree", "decoration", "plant"],
  },

  // Super Heroes & Popular Characters (Marvel, Disney, etc)
  {
    unicode: "🕷️",
    shortcode: ":spider:",
    name: "Spider",
    keywords: ["spider", "marvel", "spiderman", "insect"],
  },
  {
    unicode: "🦸‍♂️",
    shortcode: ":superhero_man:",
    name: "Superhero Man",
    keywords: ["superhero", "hero", "marvel", "man", "cape", "power"],
  },
  {
    unicode: "🦸‍♀️",
    shortcode: ":superhero_woman:",
    name: "Superhero Woman",
    keywords: ["superhero", "hero", "marvel", "woman", "cape", "power"],
  },
  {
    unicode: "🦹‍♂️",
    shortcode: ":supervillain_man:",
    name: "Supervillain Man",
    keywords: ["villain", "evil", "bad", "man"],
  },
  {
    unicode: "🦹‍♀️",
    shortcode: ":supervillain_woman:",
    name: "Supervillain Woman",
    keywords: ["villain", "evil", "bad", "woman"],
  },
  {
    unicode: "🧚‍♀️",
    shortcode: ":fairy_woman:",
    name: "Fairy",
    keywords: ["fairy", "magic", "fantasy", "woman", "disney"],
  },
  {
    unicode: "🧙‍♂️",
    shortcode: ":mage_man:",
    name: "Mage",
    keywords: ["wizard", "magic", "fantasy", "man"],
  },
  {
    unicode: "👸",
    shortcode: ":princess:",
    name: "Princess",
    keywords: ["princess", "disney", "royalty", "woman", "beautiful"],
  },
  {
    unicode: "🤴",
    shortcode: ":prince:",
    name: "Prince",
    keywords: ["prince", "royalty", "man", "disney"],
  },
];

export interface EmojiGroup {
  name: string;
  description: string;
  emojis: EmojiData[];
  selectable?: boolean;
}

// Organized groups from EMOJI_DATABASE
export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    name: "Smileys",
    description: "Happy faces & emotions",
    emojis: EMOJI_DATABASE.slice(0, 90),
    selectable: false,
  },
  {
    name: "Animals",
    description: "Animals & nature",
    emojis: EMOJI_DATABASE.slice(90, 180),
    selectable: false,
  },
  {
    name: "Food & Drink",
    description: "Delicious treats",
    emojis: EMOJI_DATABASE.slice(180, 280),
    selectable: false,
  },
  {
    name: "Sports & Activities",
    description: "Games & entertainment",
    emojis: EMOJI_DATABASE.slice(280, 330),
    selectable: false,
  },
  {
    name: "Festive",
    description: "Party & celebration",
    emojis: EMOJI_DATABASE.filter((e) =>
      [
        "🎉",
        "🎊",
        "🎈",
        "🎁",
        "🎀",
        "🎂",
        "🎃",
        "🎄",
        "🎆",
        "🎇",
        "🥳",
        "✨",
      ].includes(e.unicode)
    ),
    selectable: true,
  },
  {
    name: "Hearts & Love",
    description: "Love & affection",
    emojis: EMOJI_DATABASE.filter((e) =>
      [
        "❤️",
        "🧡",
        "💛",
        "💚",
        "💙",
        "💜",
        "🖤",
        "🤍",
        "🤎",
        "💔",
        "💕",
        "💞",
        "💓",
        "💗",
        "💖",
        "💘",
        "💝",
        "💟",
      ].includes(e.unicode)
    ),
    selectable: true,
  },
  {
    name: "Magic & Stars",
    description: "Sparkles & magical",
    emojis: EMOJI_DATABASE.filter((e) =>
      ["⭐", "🌟", "✨", "⚡", "☄️", "💥", "🔥", "🌈"].includes(e.unicode)
    ),
    selectable: true,
  },
  {
    name: "Marvel & Heroes",
    description: "Superheroes & villains",
    emojis: EMOJI_DATABASE.filter((e) =>
      ["🕷️", "🦸‍♂️", "🦸‍♀️", "🦹‍♂️", "🦹‍♀️"].includes(e.unicode)
    ),
    selectable: true,
  },
  {
    name: "Disney & Fantasy",
    description: "Disney & magical characters",
    emojis: EMOJI_DATABASE.filter((e) =>
      ["🧚‍♀️", "🧙‍♂️", "👸", "🤴", "🐭", "🦄", "🐰"].includes(e.unicode)
    ),
    selectable: true,
  },
];
